package net.idtoki.aveobras.manager;

import java.util.logging.Logger;
import net.idtoki.aveobras.model.PartesPeer;
import net.idtoki.aveobras.group.PartesGroupBean;
import net.idtoki.aveobras.model.Partes;
import net.zylk.torque.SearchQuery;
import net.zylk.torque.BaseQuery;
import net.zylk.torque.TorqueUtils;
import net.zylk.torque.manager.BaseManager;
import org.apache.torque.TorqueException;
import java.util.Enumeration;


import net.idtoki.aveobras.model.Maquinarias;
import net.idtoki.aveobras.model.MaquinariasPeer;
import net.idtoki.aveobras.model.Operarios;
import net.idtoki.aveobras.model.OperariosPeer;
import net.idtoki.aveobras.model.Uejecuciones;
import net.idtoki.aveobras.model.UejecucionesPeer;

import org.apache.torque.util.Criteria;
import org.apache.torque.util.UniqueList;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;

/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Oct 25 17:01:04 CEST 2006]
 *
 */
public abstract class BasePartesManager extends BaseManager
{
	protected static final Logger logger = Logger.getLogger(
	   "net.idtoki.aveobras.managers.BasePartesManager");

	public static final Criteria buildSearchCriteria(DinamicGridBean dgb)
	{
		return BaseManager.buildSearchCriteria(dgb, new PartesManager());
	}

	public static final Criteria buildSearchCriteria(String query, int offset, int limit)
	{
		return BaseManager.buildSearchCriteria(query, offset, limit, new PartesManager());
	}

	public static final Criteria buildSearchCriteria(String query)
	{
		return BaseManager.buildSearchCriteria(query, new PartesManager());
	}

	protected void addOrSearchCriteria(Criteria criteria,String campo,String valor, String condicion){
		Criteria.Criterion criterion = PartesManager.getSearchCriterion(campo,valor, condicion);
		//Si existe ya un criterion hay que utilizarlo para añadir el or sino utilizará un and
		Enumeration enumeration =criteria.elements();
		if(enumeration.hasMoreElements()){
			Criteria.Criterion cr = (Criteria.Criterion) enumeration.nextElement();
			cr.or(criterion);
		}else{
			criteria.or(criterion);
		}
	}

	protected void addAndSearchCriteria(Criteria criteria,String campo, String valor, String condicion){
		Criteria.Criterion criterion = PartesManager.getSearchCriterion(campo,valor, condicion);
		criteria.and(criterion);
	}

	protected static Criteria.Criterion getSearchCriterion(String campo,String valor, String condicion){
        Criteria criteria =  new Criteria();
        Criteria.Criterion criterion = null;

			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.IDPARTE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.IDPARTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.IDPARTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.IDPARTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.IDPARTE,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.IDUEJECUCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.IDUEJECUCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.IDUEJECUCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.IDUEJECUCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.IDUEJECUCION,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.IDOPERARIO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.IDOPERARIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.IDOPERARIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.IDOPERARIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.IDOPERARIO,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.IDMAQUINARIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.IDMAQUINARIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.IDMAQUINARIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.IDMAQUINARIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.IDMAQUINARIA,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.FECHA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.FECHA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.FECHA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.FECHA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.FECHA,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.REFERENCIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.REFERENCIA,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.DESCRIPCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.DESCRIPCION,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.OBSERVACIONES)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.OBSERVACIONES,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.HORAS)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.HORAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.HORAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.HORAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.HORAS,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(PartesPeer.IMPORTE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,PartesPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,PartesPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,PartesPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,PartesPeer.IMPORTE,valor,true);
		}
									if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.IDMAQUINARIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.IDMAQUINARIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.IDMAQUINARIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.IDMAQUINARIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.IDMAQUINARIA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.NOMBRE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.NOMBRE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.REFERENCIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.REFERENCIA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.BASTIDOR)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.BASTIDOR,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.BASTIDOR,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.BASTIDOR,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.BASTIDOR,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.MATRICULA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.MATRICULA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.MATRICULA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.MATRICULA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.MATRICULA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.FECHAALTA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.FECHAALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.FECHAALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.FECHAALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.FECHAALTA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.FECHABAJA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.FECHABAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.FECHABAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.FECHABAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.FECHABAJA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.RESPONSABLE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.RESPONSABLE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.RESPONSABLE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.RESPONSABLE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.RESPONSABLE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.COSTE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.COSTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.COSTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.COSTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.COSTE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.MODELO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.MODELO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.MODELO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.MODELO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.MODELO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.MARCA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.MARCA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.MARCA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.MARCA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.MARCA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.TIPO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.TIPO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.TIPO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.TIPO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.TIPO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.ALQUILADO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.ALQUILADO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.ALQUILADO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.ALQUILADO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.ALQUILADO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(MaquinariasPeer.OBSERVACIONES)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,MaquinariasPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,MaquinariasPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,MaquinariasPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,MaquinariasPeer.OBSERVACIONES,valor,true);
		}
													if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.IDOPERARIO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.IDOPERARIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.IDOPERARIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.IDOPERARIO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.IDOPERARIO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.IDCATEGORIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.IDCATEGORIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.IDCATEGORIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.IDCATEGORIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.IDCATEGORIA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.REFERENCIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.REFERENCIA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.NIF)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.NIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.NIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.NIF,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.NIF,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.NOMBRE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.NOMBRE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.APELLIDOUNO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.APELLIDOUNO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.APELLIDOUNO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.APELLIDOUNO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.APELLIDOUNO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.APELLIDODOS)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.APELLIDODOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.APELLIDODOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.APELLIDODOS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.APELLIDODOS,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.FECHAALTA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.FECHAALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.FECHAALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.FECHAALTA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.FECHAALTA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.FECHABAJA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.FECHABAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.FECHABAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.FECHABAJA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.FECHABAJA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.NUMEROSS)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.NUMEROSS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.NUMEROSS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.NUMEROSS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.NUMEROSS,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.DIRECCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.DIRECCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.DIRECCION,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.CP)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.CP,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.CP,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.IDLOCALIDAD)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.IDLOCALIDAD,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.IDLOCALIDAD,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.IDLOCALIDAD,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.IDLOCALIDAD,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.TELEFONO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.TELEFONO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.TELEFONO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.MOVIL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.MOVIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.MOVIL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.EMAIL)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.EMAIL,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.EMAIL,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.COSTE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.COSTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.COSTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.COSTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.COSTE,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.EXTERNO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.EXTERNO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.EXTERNO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.EXTERNO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.EXTERNO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(OperariosPeer.OBSERVACIONES)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,OperariosPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,OperariosPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,OperariosPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,OperariosPeer.OBSERVACIONES,valor,true);
		}
													if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.IDUEJECUCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.IDUEJECUCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.IDUEJECUCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.IDUEJECUCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.IDUEJECUCION,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.IDOBRA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.IDOBRA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.IDOBRA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.IDOBRA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.IDOBRA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.IDSUBCAPITULO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.IDSUBCAPITULO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.IDSUBCAPITULO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.IDSUBCAPITULO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.IDSUBCAPITULO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.FECHACOMIENZO)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.FECHACOMIENZO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.FECHACOMIENZO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.FECHACOMIENZO,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.FECHACOMIENZO,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.FECHAFIN)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.FECHAFIN,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.FECHAFIN,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.FECHAFIN,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.FECHAFIN,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.HORASESTIMADAS)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.HORASESTIMADAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.HORASESTIMADAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.HORASESTIMADAS,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.HORASESTIMADAS,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.REFERENCIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.REFERENCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.REFERENCIA,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.DESCRIPCION)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.DESCRIPCION,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.DESCRIPCION,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.OBSERVACIONES)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.OBSERVACIONES,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.OBSERVACIONES,valor,true);
		}
					if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(UejecucionesPeer.IMPORTE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,UejecucionesPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,UejecucionesPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,UejecucionesPeer.IMPORTE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,UejecucionesPeer.IMPORTE,valor,true);
		}
						
		return criterion;
	}

	public static final PartesGroupBean getPartess() {
    	return BasePartesManager.getPartess(false);
	}

	public static final PartesGroupBean getPartess(boolean paginado) {
    	return BasePartesManager.getPartess(new Criteria(), paginado,0);
	}

	public static final PartesGroupBean getPartess(Criteria c) {
		return BasePartesManager.getPartess(c,false,0);
	}

	public static final PartesGroupBean getPartess(Criteria criteria,boolean paginado, int pagina) {
		PartesGroupBean objPartesGroupBean = new PartesGroupBean();
		objPartesGroupBean.setPaginaActual(pagina);
		objPartesGroupBean.setPartess(criteria, paginado);
		return objPartesGroupBean;
	}

							
	public static final Partes getPartes(int id_Idparte) {
		Criteria c = new Criteria();
			c.add(PartesPeer.IDPARTE, id_Idparte);
			return BasePartesManager.PartessGroupBean2Partes(BasePartesManager.getPartess(c));
	}

	public static final Partes PartessGroupBean2Partes(PartesGroupBean obj){
		if(obj.size() == 1)
			return obj.getPartes(0);
		else
			return null;
	}

	private static void updatePartesAttribute(int id_Idparte, String valor, String campo) throws Exception
	{
		Partes obj = BasePartesManager.getPartes(id_Idparte);
			if(campo.equals(PartesPeer.IDPARTE))
					obj.setIdparte(Integer.parseInt(valor)); //int
					if(campo.equals(PartesPeer.IDUEJECUCION))
					obj.setIduejecucion(Integer.parseInt(valor)); //int
					if(campo.equals(PartesPeer.IDOPERARIO))
					obj.setIdoperario(Integer.parseInt(valor)); //int
					if(campo.equals(PartesPeer.IDMAQUINARIA))
					obj.setIdmaquinaria(Integer.parseInt(valor)); //int
					if(campo.equals(PartesPeer.FECHA))
					obj.setFecha(valor); //String
					if(campo.equals(PartesPeer.REFERENCIA))
					obj.setReferencia(valor); //String
					if(campo.equals(PartesPeer.DESCRIPCION))
					obj.setDescripcion(valor); //String
					if(campo.equals(PartesPeer.OBSERVACIONES))
					obj.setObservaciones(valor); //String
					if(campo.equals(PartesPeer.HORAS))
					obj.setHoras(Double.parseDouble(valor)); //double
					if(campo.equals(PartesPeer.IMPORTE))
					obj.setImporte(Double.parseDouble(valor)); //double
					obj.save();
	}

	public static void updateIdparte(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.IDPARTE);
	}
	public static void updateIduejecucion(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.IDUEJECUCION);
	}
	public static void updateIdoperario(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.IDOPERARIO);
	}
	public static void updateIdmaquinaria(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.IDMAQUINARIA);
	}
	public static void updateFecha(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.FECHA);
	}
	public static void updateReferencia(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.REFERENCIA);
	}
	public static void updateDescripcion(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.DESCRIPCION);
	}
	public static void updateObservaciones(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.OBSERVACIONES);
	}
	public static void updateHoras(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.HORAS);
	}
	public static void updateImporte(int id_Idparte, String valor) throws Exception
	{
		updatePartesAttribute(id_Idparte, valor, PartesPeer.IMPORTE);
	}

						public void addJoins(Criteria criteria)
	{
																																																	criteria.addJoin(PartesPeer.IDMAQUINARIA,MaquinariasPeer.IDMAQUINARIA);
																																																													criteria.addJoin(PartesPeer.IDOPERARIO,OperariosPeer.IDOPERARIO);
																																																													criteria.addJoin(PartesPeer.IDUEJECUCION,UejecucionesPeer.IDUEJECUCION);
															}
	

  public static void deletePartes(int id_Idparte) throws TorqueException
  {
  	PartesPeer.doDelete(PartesManager.getPartes(id_Idparte));
  }

  public static Partes addUpdatePartes(Partes obj) throws TorqueException
  {
	PartesGroupBean gb = new PartesGroupBean();
	gb.setElemento(obj);
	gb.save();
	return obj;
  }

}

