package net.idtoki.aveobras.manager;

import java.util.logging.Logger;
import net.idtoki.aveobras.model.ProvinciasPeer;
import net.idtoki.aveobras.group.ProvinciasGroupBean;
import net.idtoki.aveobras.model.Provincias;
import net.zylk.torque.SearchQuery;
import net.zylk.torque.BaseQuery;
import net.zylk.torque.TorqueUtils;
import net.zylk.torque.manager.BaseManager;
import org.apache.torque.TorqueException;
import java.util.Enumeration;



import org.apache.torque.util.Criteria;
import org.apache.torque.util.UniqueList;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;

/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Oct 25 17:01:04 CEST 2006]
 *
 */
public abstract class BaseProvinciasManager extends BaseManager
{
	protected static final Logger logger = Logger.getLogger(
	   "net.idtoki.aveobras.managers.BaseProvinciasManager");

	public static final Criteria buildSearchCriteria(DinamicGridBean dgb)
	{
		return BaseManager.buildSearchCriteria(dgb, new ProvinciasManager());
	}

	public static final Criteria buildSearchCriteria(String query, int offset, int limit)
	{
		return BaseManager.buildSearchCriteria(query, offset, limit, new ProvinciasManager());
	}

	public static final Criteria buildSearchCriteria(String query)
	{
		return BaseManager.buildSearchCriteria(query, new ProvinciasManager());
	}

	protected void addOrSearchCriteria(Criteria criteria,String campo,String valor, String condicion){
		Criteria.Criterion criterion = ProvinciasManager.getSearchCriterion(campo,valor, condicion);
		//Si existe ya un criterion hay que utilizarlo para añadir el or sino utilizará un and
		Enumeration enumeration =criteria.elements();
		if(enumeration.hasMoreElements()){
			Criteria.Criterion cr = (Criteria.Criterion) enumeration.nextElement();
			cr.or(criterion);
		}else{
			criteria.or(criterion);
		}
	}

	protected void addAndSearchCriteria(Criteria criteria,String campo, String valor, String condicion){
		Criteria.Criterion criterion = ProvinciasManager.getSearchCriterion(campo,valor, condicion);
		criteria.and(criterion);
	}

	protected static Criteria.Criterion getSearchCriterion(String campo,String valor, String condicion){
        Criteria criteria =  new Criteria();
        Criteria.Criterion criterion = null;

			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ProvinciasPeer.IDPROVINCIA)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ProvinciasPeer.IDPROVINCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ProvinciasPeer.IDPROVINCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ProvinciasPeer.IDPROVINCIA,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ProvinciasPeer.IDPROVINCIA,valor,true);
		}
			if(campo.equals("all") || campo.equals(BaseManager.campoToLowerCase(ProvinciasPeer.NOMBRE)))
		{
			if(condicion.equals(BaseQuery.SingleQuery.EQUAL_CONDITION))
				criterion = TorqueUtils.addOrEqualCriteria(criterion,ProvinciasPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LIKE_CONDITION))
				criterion = TorqueUtils.addOrLikeCriteria(criterion,ProvinciasPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.LESS_CONDITION))
				criterion = TorqueUtils.addOrLessCriteria(criterion,ProvinciasPeer.NOMBRE,valor,true);
			else if (condicion.equals(BaseQuery.SingleQuery.GREATER_CONDITION))
				criterion = TorqueUtils.addOrGreaterCriteria(criterion,ProvinciasPeer.NOMBRE,valor,true);
		}
		
		return criterion;
	}

	public static final ProvinciasGroupBean getProvinciass() {
    	return BaseProvinciasManager.getProvinciass(false);
	}

	public static final ProvinciasGroupBean getProvinciass(boolean paginado) {
    	return BaseProvinciasManager.getProvinciass(new Criteria(), paginado,0);
	}

	public static final ProvinciasGroupBean getProvinciass(Criteria c) {
		return BaseProvinciasManager.getProvinciass(c,false,0);
	}

	public static final ProvinciasGroupBean getProvinciass(Criteria criteria,boolean paginado, int pagina) {
		ProvinciasGroupBean objProvinciasGroupBean = new ProvinciasGroupBean();
		objProvinciasGroupBean.setPaginaActual(pagina);
		objProvinciasGroupBean.setProvinciass(criteria, paginado);
		return objProvinciasGroupBean;
	}

							
	public static final Provincias getProvincias(int id_Idprovincia) {
		Criteria c = new Criteria();
			c.add(ProvinciasPeer.IDPROVINCIA, id_Idprovincia);
			return BaseProvinciasManager.ProvinciassGroupBean2Provincias(BaseProvinciasManager.getProvinciass(c));
	}

	public static final Provincias ProvinciassGroupBean2Provincias(ProvinciasGroupBean obj){
		if(obj.size() == 1)
			return obj.getProvincias(0);
		else
			return null;
	}

	private static void updateProvinciasAttribute(int id_Idprovincia, String valor, String campo) throws Exception
	{
		Provincias obj = BaseProvinciasManager.getProvincias(id_Idprovincia);
			if(campo.equals(ProvinciasPeer.IDPROVINCIA))
					obj.setIdprovincia(Integer.parseInt(valor)); //int
					if(campo.equals(ProvinciasPeer.NOMBRE))
					obj.setNombre(valor); //String
					obj.save();
	}

	public static void updateIdprovincia(int id_Idprovincia, String valor) throws Exception
	{
		updateProvinciasAttribute(id_Idprovincia, valor, ProvinciasPeer.IDPROVINCIA);
	}
	public static void updateNombre(int id_Idprovincia, String valor) throws Exception
	{
		updateProvinciasAttribute(id_Idprovincia, valor, ProvinciasPeer.NOMBRE);
	}

			public void addJoins(Criteria criteria)
	{
	 //no tiene claves externas asi que el metodo no hace nada
	}
	

  public static void deleteProvincias(int id_Idprovincia) throws TorqueException
  {
  	ProvinciasPeer.doDelete(ProvinciasManager.getProvincias(id_Idprovincia));
  }

  public static Provincias addUpdateProvincias(Provincias obj) throws TorqueException
  {
	ProvinciasGroupBean gb = new ProvinciasGroupBean();
	gb.setElemento(obj);
	gb.save();
	return obj;
  }

}

