package net.idtoki.aveobras.manager;

import net.idtoki.aveobras.model.OperariosPeer;
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class OperariosManager
    extends BaseOperariosManager
{
	public static boolean borraOperarios(int idBorrar) {

		Criteria c=new Criteria();
		c.add(OperariosPeer.IDOPERARIO, idBorrar);
		boolean bRet = false;
		try {
			OperariosPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar el Subcapitulo");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}	
}


