package net.idtoki.aveobras.manager;

import net.idtoki.aveobras.group.PartesGroupBean;
import net.idtoki.aveobras.model.Partes;
import net.idtoki.aveobras.model.PartesPeer;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class PartesManager
    extends BasePartesManager
{
	public static boolean borraPartes(int idBorrar) {

		Criteria c=new Criteria();
		c.add(PartesPeer.IDPARTE, idBorrar);
		boolean bRet = false;
		try {
			PartesPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar la Obra");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}	
	
	public static void duplicarPartes(int idDuplicar) {

		Criteria c=new Criteria();
		c.add(PartesPeer.IDPARTE, idDuplicar);
		try {
			Partes ob = PartesManager.getPartess(c).getPartes(0);
			 ob.setNew(true);
			 ob.setIdparte(-1);
			 ob.setReferencia("(Duplicado)");
			 PartesGroupBean ogb = new PartesGroupBean();
			 ogb.setElemento(ob);
			 ogb.save();
		} catch (TorqueException e) {
			logger.info("No se ha podido duplicar el Parte");
			e.printStackTrace();
		}
	}		
}


