package net.idtoki.aveobras.manager;

import net.idtoki.aveobras.model.TipoincidenciasPeer;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TipoincidenciasManager
    extends BaseTipoincidenciasManager
{
	public static boolean borraTipoincidencias(int idBorrar) {

		Criteria c=new Criteria();
		c.add(TipoincidenciasPeer.IDTIPOINCIDENCIA, idBorrar);
		boolean bRet = false;
		try {
			TipoincidenciasPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar el tipo de incidencia");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}	
}


