package net.idtoki.aveobras.manager;

import net.idtoki.aveobras.group.UejecucionesGroupBean;
import net.idtoki.aveobras.model.Uejecuciones;
import net.idtoki.aveobras.model.UejecucionesPeer;
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;


/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UejecucionesManager
    extends BaseUejecucionesManager
{
	public static boolean borraUejecuciones(int idBorrar) {

		Criteria c=new Criteria();
		c.add(UejecucionesPeer.IDUEJECUCION, idBorrar);
		boolean bRet = false;
		try {
			UejecucionesPeer.doDelete(c);
			bRet = true;
		} catch (TorqueException e) {
			logger.info("No se ha podido borrar la unidad de ejecución");
			e.printStackTrace();
			bRet = false;
		}
		return bRet;
	}
	public static void duplicarUejecuciones(int idDuplicar) {

		Criteria c=new Criteria();
		c.add(UejecucionesPeer.IDUEJECUCION, idDuplicar);
		try {
			Uejecuciones uej = UejecucionesManager.getUejecucioness(c).getUejecuciones(0);
			uej.setNew(true);
			uej.setIduejecucion(-1);
			uej.setDescripcion("(Duplicado)"+uej.getDescripcion());
			UejecucionesGroupBean ugb = new UejecucionesGroupBean();
			ugb.setElemento(uej);
			ugb.save();			
		} catch (TorqueException e) {
			logger.info("No se ha podido duplicar la Unidad de Ejecución");
			e.printStackTrace();
		}
	}	
	public static void duplicarUejecuciones(int idDuplicar, int idObra) {

		Criteria c=new Criteria();
		c.add(UejecucionesPeer.IDUEJECUCION, idDuplicar);
		try {
			Uejecuciones uej = UejecucionesManager.getUejecucioness(c).getUejecuciones(0);
			uej.setNew(true);
			uej.setIduejecucion(-1);
			uej.setDescripcion("(Duplicado)"+uej.getDescripcion());
			uej.setIdobra(idObra);
			UejecucionesGroupBean ugb = new UejecucionesGroupBean();
			ugb.setElemento(uej);
			ugb.save();			
		} catch (TorqueException e) {
			logger.info("No se ha podido duplicar la Unidad de Ejecución");
			e.printStackTrace();
		}
	}
}


