package net.idtoki.aveobras.model.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Wed Oct 25 17:01:04 CEST 2006]
  *
  */
public class IncidenciasMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "net.idtoki.aveobras.model.map.IncidenciasMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("AVEOBRAS-DB");

        dbMap.addTable("incidencias");
        TableMap tMap = dbMap.getTable("incidencias");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);

        // this might need upgrading based on what all the databases
        // need, but for now assume one parameter.
          tMap.setPrimaryKeyMethodInfo("incidencias_idincidencia_seq");

              tMap.addPrimaryKey("incidencias.IDINCIDENCIA", new Integer(0));
                    tMap.addForeignKey(
                "incidencias.IDUEJECUCION", new Integer(0) , "uejecuciones" ,
                "iduejecucion");
                    tMap.addForeignKey(
                "incidencias.IDOPERARIO", new Integer(0) , "operarios" ,
                "idoperario");
                    tMap.addForeignKey(
                "incidencias.IDMAQUINARIA", new Integer(0) , "maquinarias" ,
                "idmaquinaria");
                    tMap.addForeignKey(
                "incidencias.IDTIPOINCIDENCIA", new Integer(0) , "tipoincidencias" ,
                "idtipoincidencia");
                    tMap.addColumn("incidencias.FECHA", "");
                    tMap.addColumn("incidencias.REFERENCIA", "");
                    tMap.addColumn("incidencias.DESCRIPCION", "");
                    tMap.addColumn("incidencias.OBSERVACIONES", "");
                    tMap.addColumn("incidencias.HORAS", new Double(0));
                    tMap.addColumn("incidencias.IMPORTE", new Double(0));
                    tMap.addColumn("incidencias.KILOMETROS", new Double(0));
                    tMap.addColumn("incidencias.TONELAJE", new Double(0));
          }
}
