package net.idtoki.aveobras.model.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Wed Oct 25 17:01:04 CEST 2006]
  *
  */
public class MaquinariasMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "net.idtoki.aveobras.model.map.MaquinariasMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("AVEOBRAS-DB");

        dbMap.addTable("maquinarias");
        TableMap tMap = dbMap.getTable("maquinarias");

        tMap.setPrimaryKeyMethod(TableMap.NATIVE);

        // this might need upgrading based on what all the databases
        // need, but for now assume one parameter.
          tMap.setPrimaryKeyMethodInfo("maquinarias_idmaquinaria_seq");

              tMap.addPrimaryKey("maquinarias.IDMAQUINARIA", new Integer(0));
                    tMap.addColumn("maquinarias.NOMBRE", "");
                    tMap.addColumn("maquinarias.REFERENCIA", "");
                    tMap.addColumn("maquinarias.BASTIDOR", "");
                    tMap.addColumn("maquinarias.MATRICULA", "");
                    tMap.addColumn("maquinarias.FECHAALTA", "");
                    tMap.addColumn("maquinarias.FECHABAJA", "");
                    tMap.addColumn("maquinarias.RESPONSABLE", "");
                    tMap.addColumn("maquinarias.COSTE", new Double(0));
                    tMap.addColumn("maquinarias.MODELO", "");
                    tMap.addColumn("maquinarias.MARCA", "");
                    tMap.addColumn("maquinarias.TIPO", "");
                    tMap.addColumn("maquinarias.ALQUILADO", new Integer(0));
                    tMap.addColumn("maquinarias.OBSERVACIONES", "");
          }
}
