package net.idtoki.aveobras.model;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import net.zylk.tools.ajax.AjaxUtils;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

  
  
/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Oct 25 17:01:04 CEST 2006]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Localidades
 */
public abstract class BaseLocalidades extends BaseObject
{
    /** The Peer class */
    private static final LocalidadesPeer peer =
        new LocalidadesPeer();

                                            
    /** The value for the idlocalidad field */
    private int idlocalidad = -1;
                                          
    /** The value for the idprovincia field */
    private int idprovincia = 0;
                                                
    /** The value for the nombre field */
    private String nombre = "";
  
    
    /**
     * Get the Idlocalidad
     *
     * @return int
     */
    public int getIdlocalidad()
    {
        return idlocalidad;
    }

                                              
    /**
     * Set the value of Idlocalidad
     *
     * @param v new value
     */
    public void setIdlocalidad(int v) throws TorqueException
    {
    
                  if (this.idlocalidad != v)
              {
            this.idlocalidad = v;
            setModified(true);
        }
    
          
                                  
                                                    
                                                    
                                }
  
    /**
     * Get the Idprovincia
     *
     * @return int
     */
    public int getIdprovincia()
    {
        return idprovincia;
    }

                              
    /**
     * Set the value of Idprovincia
     *
     * @param v new value
     */
    public void setIdprovincia(int v) throws TorqueException
    {
    
                  if (this.idprovincia != v)
              {
            this.idprovincia = v;
            setModified(true);
        }
    
                          
                if (aProvincias != null && !(aProvincias.getIdprovincia() == v))
                {
            aProvincias = null;
        }
      
              }
  
    /**
     * Get the Nombre
     *
     * @return String
     */
    public String getNombre()
    {
        return nombre;
    }

                        
    /**
     * Set the value of Nombre
     *
     * @param v new value
     */
    public void setNombre(String v) 
    {
    
                  if (!ObjectUtils.equals(this.nombre, v))
              {
            this.nombre = v;
            setModified(true);
        }
    
          
              }
  
      
    
                  
    
        private Provincias aProvincias;

    /**
     * Declares an association between this object and a Provincias object
     *
     * @param v Provincias
     * @throws TorqueException
     */
    public void setProvincias(Provincias v) throws TorqueException
    {
            if (v == null)
        {
                          setIdprovincia( 0);
              }
        else
        {
            setIdprovincia(v.getIdprovincia());
        }
            aProvincias = v;
    }

                                            
    /**
     * Get the associated Provincias object
     *
     * @return the associated Provincias object
     * @throws TorqueException
     */
    public Provincias getProvincias() throws TorqueException
    {
        if (aProvincias == null && (this.idprovincia != 0))
        {
                          aProvincias = ProvinciasPeer.retrieveByPK(SimpleKey.keyFor(this.idprovincia));
              
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Provincias obj = ProvinciasPeer.retrieveByPK(this.idprovincia);
               obj.addLocalidadess(this);
            */
        }
        return aProvincias;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
         */
    public void setProvinciasKey(ObjectKey key) throws TorqueException
    {
      
                        setIdprovincia(((NumberKey) key).intValue());
                  }
       
                                
            
      
    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getClientess(new Criteria())
     *
     * @throws TorqueException
     */
    public List getClientess() throws TorqueException
    {
                  return getClientess(new Criteria(10));
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades has previously
     * been saved, it will retrieve related Clientess from storage.
     * If this Localidades is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getClientess(Criteria criteria) throws TorqueException
    {
                            criteria.add(ClientesPeer.IDLOCALIDAD, getIdlocalidad());
                            return ClientesPeer.doSelect(criteria);
          }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getClientess(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getClientess(Connection con) throws TorqueException
    {
                  return getClientess(new Criteria(10), con);
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades has previously
     * been saved, it will retrieve related Clientess from storage.
     * If this Localidades is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getClientess(Criteria criteria, Connection con)
            throws TorqueException
    {
                             criteria.add(ClientesPeer.IDLOCALIDAD, getIdlocalidad());
                             return ClientesPeer.doSelect(criteria, con);
           }

                  
              
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades is new, it will return
     * an empty collection; or if this Localidades has previously
     * been saved, it will retrieve related Clientess from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Localidades.
     */
    protected List getClientessJoinLocalidades(Criteria criteria)
        throws TorqueException
    {
            
                        criteria.add(ClientesPeer.IDLOCALIDAD, getIdlocalidad());
                                    return ClientesPeer.doSelectJoinLocalidades(criteria);
                }
                            


                          
            
      
    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getObrass(new Criteria())
     *
     * @throws TorqueException
     */
    public List getObrass() throws TorqueException
    {
                  return getObrass(new Criteria(10));
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades has previously
     * been saved, it will retrieve related Obrass from storage.
     * If this Localidades is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getObrass(Criteria criteria) throws TorqueException
    {
                            criteria.add(ObrasPeer.IDLOCALIDAD, getIdlocalidad());
                            return ObrasPeer.doSelect(criteria);
          }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getObrass(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getObrass(Connection con) throws TorqueException
    {
                  return getObrass(new Criteria(10), con);
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades has previously
     * been saved, it will retrieve related Obrass from storage.
     * If this Localidades is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getObrass(Criteria criteria, Connection con)
            throws TorqueException
    {
                             criteria.add(ObrasPeer.IDLOCALIDAD, getIdlocalidad());
                             return ObrasPeer.doSelect(criteria, con);
           }

                        
              
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades is new, it will return
     * an empty collection; or if this Localidades has previously
     * been saved, it will retrieve related Obrass from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Localidades.
     */
    protected List getObrassJoinClientes(Criteria criteria)
        throws TorqueException
    {
            
                        criteria.add(ObrasPeer.IDLOCALIDAD, getIdlocalidad());
                                    return ObrasPeer.doSelectJoinClientes(criteria);
                }
                  
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades is new, it will return
     * an empty collection; or if this Localidades has previously
     * been saved, it will retrieve related Obrass from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Localidades.
     */
    protected List getObrassJoinLocalidades(Criteria criteria)
        throws TorqueException
    {
            
                        criteria.add(ObrasPeer.IDLOCALIDAD, getIdlocalidad());
                                    return ObrasPeer.doSelectJoinLocalidades(criteria);
                }
                            


                          
            
      
    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getOperarioss(new Criteria())
     *
     * @throws TorqueException
     */
    public List getOperarioss() throws TorqueException
    {
                  return getOperarioss(new Criteria(10));
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades has previously
     * been saved, it will retrieve related Operarioss from storage.
     * If this Localidades is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getOperarioss(Criteria criteria) throws TorqueException
    {
                            criteria.add(OperariosPeer.IDLOCALIDAD, getIdlocalidad());
                            return OperariosPeer.doSelect(criteria);
          }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getOperarioss(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getOperarioss(Connection con) throws TorqueException
    {
                  return getOperarioss(new Criteria(10), con);
          }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades has previously
     * been saved, it will retrieve related Operarioss from storage.
     * If this Localidades is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getOperarioss(Criteria criteria, Connection con)
            throws TorqueException
    {
                             criteria.add(OperariosPeer.IDLOCALIDAD, getIdlocalidad());
                             return OperariosPeer.doSelect(criteria, con);
           }

                        
              
                    
                    
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades is new, it will return
     * an empty collection; or if this Localidades has previously
     * been saved, it will retrieve related Operarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Localidades.
     */
    protected List getOperariossJoinCategorias(Criteria criteria)
        throws TorqueException
    {
            
                        criteria.add(OperariosPeer.IDLOCALIDAD, getIdlocalidad());
                                    return OperariosPeer.doSelectJoinCategorias(criteria);
                }
                  
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Localidades is new, it will return
     * an empty collection; or if this Localidades has previously
     * been saved, it will retrieve related Operarioss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Localidades.
     */
    protected List getOperariossJoinLocalidades(Criteria criteria)
        throws TorqueException
    {
            
                        criteria.add(OperariosPeer.IDLOCALIDAD, getIdlocalidad());
                                    return OperariosPeer.doSelectJoinLocalidades(criteria);
                }
                            


          
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("Idlocalidad");
              fieldNames.add("Idprovincia");
              fieldNames.add("Nombre");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("Idlocalidad"))
        {
                return new Integer(getIdlocalidad());
            }
          if (name.equals("Idprovincia"))
        {
                return new Integer(getIdprovincia());
            }
          if (name.equals("Nombre"))
        {
                return getNombre();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(LocalidadesPeer.IDLOCALIDAD))
        {
                return new Integer(getIdlocalidad());
            }
          if (name.equals(LocalidadesPeer.IDPROVINCIA))
        {
                return new Integer(getIdprovincia());
            }
          if (name.equals(LocalidadesPeer.NOMBRE))
        {
                return getNombre();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getIdlocalidad());
            }
              if (pos == 1)
        {
                return new Integer(getIdprovincia());
            }
              if (pos == 2)
        {
                return getNombre();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(LocalidadesPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    LocalidadesPeer.doInsert((Localidades) this, con);
                    setNew(false);
                }
                else
                {
                    LocalidadesPeer.doUpdate((Localidades) this, con);
                }
            }

                                      
                
                                                  
                
                                                  
                
                                  alreadyInSave = false;
        }
      }

                        
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key idlocalidad ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setIdlocalidad(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setIdlocalidad(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getIdlocalidad());
      }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public Localidades copy() throws TorqueException
    {
        return copyInto(new Localidades());
    }
  
    protected Localidades copyInto(Localidades copyObj) throws TorqueException
    {
          copyObj.setIdlocalidad(idlocalidad);
          copyObj.setIdprovincia(idprovincia);
          copyObj.setNombre(nombre);
  
                            copyObj.setIdlocalidad( -1);
                        
                                      
                                                  
                                                  
                            return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public LocalidadesPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Localidades:\n");
        str.append("Idlocalidad = ")
               .append(getIdlocalidad())
             .append("\n");
        str.append("Idprovincia = ")
               .append(getIdprovincia())
             .append("\n");
        str.append("Nombre = ")
               .append(getNombre())
             .append("\n");
        return(str.toString());
    }
    public String getComplexId()
    {
    ArrayList a = new ArrayList();
      	          a.add(Integer.toString(this.getIdlocalidad()));
                return  AjaxUtils.concatenateIdFields(a);
    }
}
