
package net.idtoki.aveobras.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Clientes
    extends net.idtoki.aveobras.model.BaseClientes
    implements Persistent
{
	private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.controller.Clientes");
	
	public String getNombreClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getNombre());
	}
	public String getIdlocalidadClientesParsed()
	{
		String localidad=null;
		try
		{
			localidad=this.getLocalidades().getIdlocalidad() + "-" + this.getLocalidades().getNombreLocalidadesParsed();
		}
		catch (TorqueException te) {
			logger.severe("No se ha podido localizar el modelo. public String getIdlocalidadParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(localidad);
	}
	public String getFechaaltaClientesParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFechaalta(),"-"));
	}
	public String getFechabajaClientesParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFechabaja(),"-"));
	}	
	public String getContactoClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getContacto());
	}	
	public String getCifClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getCif());
	}
	public String getRazonsocialClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getRazonsocial());
	}	
	public String getDireccionClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getDireccion());
	}
	public String getCpClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getCp());
	}
	public String getTelefonoClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getTelefono());
	}
	public String getFaxClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getFax());
	}
	public String getEmailClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getEmail());
	}
	public String getWwwClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getWww());
	}	
	public String getObservacionesClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getObservaciones());
	}
	public String getReferenciaClientesParsed()
	{
		return FormatUtils.genericParsedStr(this.getReferencia());
	}
	public String getDeleteClientes()
	{
		return "<a href='#' class='eliminar' id='getDeleteClientes" + this.getIdcliente() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditClientes()
	{
		return "<a href='#' class='edicion' id='getEditClientes" + this.getIdcliente() + "'>&#160;&#160;&#160;&#160;</a>";
	}		
}
