
package net.idtoki.aveobras.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Incidencias
    extends net.idtoki.aveobras.model.BaseIncidencias
    implements Persistent
{
	private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.controller.Incidencias");
	
	public String getIdoperarioIncidenciasParsed()
	{
		String operario=null;
		try
		{
			operario= this.getOperarios().getIdoperario() + "-" + this.getOperarios().getNombreOperariosParsed()+ " " + this.getOperarios().getApellidounoOperariosParsed();	
		}
		catch(TorqueException te)
		{
			logger.severe("No se ha podido localizar el operario. public String getIdoperarioIncidenciasParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(operario);
	}
	public String getIdmaquinariaIncidenciasParsed()
	{
		String maquinaria=null;
		try
		{
			maquinaria= this.getMaquinarias().getIdmaquinaria() + "-" + this.getMaquinarias().getMatriculaMaquinariasParsed() + "-" + this.getMaquinarias().getNombreMaquinariasParsed();	
		}
		catch(TorqueException te)
		{
			logger.severe("No se ha podido localizar la maquinaria. public String getIdmaquinariaIncidenciasParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(maquinaria);
	}	
	public String getIduejecucionIncidenciasParsed()
	{
		String uejecucion=null;
		try
		{
			uejecucion= this.getUejecuciones().getIduejecucion() + "-" + this.getUejecuciones().getIdsubcapituloUejecucionesParsed()+ " (" + this.getUejecuciones().getIdobraUejecucionesParsed()+")";	
		}
		catch(TorqueException te)
		{
			logger.severe("No se ha podido localizar la unidad de ejecucion. public String getIduejecucionIncidenciasParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(uejecucion);
	}	
	public String getIdtipoincidenciaIncidenciasParsed()
	{
		String tipoincidencia=null;
		try
		{
			tipoincidencia= this.getTipoincidencias().getIdtipoincidencia() + "-" + this.getTipoincidencias().getDescripcionTipoincidenciasParsed();	
		}
		catch(TorqueException te)
		{
			logger.severe("No se ha podido localizar el tipo de incidencia. public String getIdtipoincidenciaIncidenciasParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(tipoincidencia);
	}	
	public String getFechaIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFecha(),"-"));
	}	
	public String getDescripcionIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getDescripcion());
	}	
	public String getObservacionesIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getObservaciones());
	}	
	public String getHorasIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getHoras()+"");
	}	
	public String getImporteIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getImporte()+"");
	}	
	public String getKilometrosIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getKilometros()+"");
	}	
	public String getTonelajeIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getTonelaje()+"");
	}	

	public String getReferenciaIncidenciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getReferencia());
	}
	public String getDeleteIncidencias()
	{
		return "<a href='#' class='eliminar' id='getDeleteIncidencias" + this.getIdincidencia() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getDuplicarIncidencias()
	{
		return "<a href='#' class='duplicar' id='getDuplicarIncidencias" + this.getIdincidencia() + "'>&#160;&#160;&#160;&#160;</a>";
	}		
	public String getEditIncidencias()
	{
		return "<a href='#' class='edicion' id='getEditIncidencias" + this.getIdincidencia() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
}
