
package net.idtoki.aveobras.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Maquinarias
    extends net.idtoki.aveobras.model.BaseMaquinarias
    implements Persistent
{
	private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.controller.Maquinarias");
	
	
	public String getNombreMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getNombre());
	}
	public String getMatriculaMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getMatricula());
	}
	public String getFechaaltaMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFechaalta(),"-"));
	}
	public String getFechabajaMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFechabaja(),"-"));
	}	
	public String getResponsableMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getResponsable());
	}	
	public String getCosteMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getCoste()+"");
	}
	public String getModeloMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getModelo());
	}
	public String getMarcaMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getMarca());
	}
	public String getTipoMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getTipo());
	}
	public String getBastidorMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getBastidor());
	}
	public String getReferenciaMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getReferencia());
	}

	public String getAlquiladoMaquinariasParsed()
	{
		return FormatUtils.genericParsedStr(this.getAlquilado()+"");
	}
	public String getAlquiladoMaquinariasParsed2()
	{
		String cadena=null;
		switch (this.getAlquilado())
		{
		case 1:
			cadena="Sí";
			break;
		default:
			cadena="No";
			break;
		}
		return FormatUtils.genericParsedStr(cadena);
	}
	public String getDeleteMaquinarias()
	{
		return "<a href='#' class='eliminar' id='getDeleteMaquinarias" + this.getIdmaquinaria() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getEditMaquinarias()
	{
		return "<a href='#' class='edicion' id='getEditMaquinarias" + this.getIdmaquinaria() + "'>&#160;&#160;&#160;&#160;</a>";
	}		
}
