
package net.idtoki.aveobras.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Partes
    extends net.idtoki.aveobras.model.BasePartes
    implements Persistent
{
	private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.controller.Partes");
	
	public String getIdoperarioPartesParsed()
	{
		String operario=null;
		try
		{
			operario= this.getOperarios().getIdoperario() + "-" + this.getOperarios().getNombreOperariosParsed()+ " " + this.getOperarios().getApellidounoOperariosParsed();	
		}
		catch(TorqueException te)
		{
			logger.severe("No se ha podido localizar el operario. public String getIdoperarioPartesParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(operario);
	}
	public String getIdmaquinariaPartesParsed()
	{
		String maquinaria=null;
		try
		{
			maquinaria= this.getMaquinarias().getIdmaquinaria() + "-" + this.getMaquinarias().getMatriculaMaquinariasParsed() + "-" + this.getMaquinarias().getNombreMaquinariasParsed();	
		}
		catch(TorqueException te)
		{
			logger.severe("No se ha podido localizar la maquinaria. public String getIdmaquinariaPartesParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(maquinaria);
	}	
	public String getIduejecucionPartesParsed()
	{
		String uejecucion=null;
		try
		{
			uejecucion= this.getUejecuciones().getIduejecucion() + "-" + this.getUejecuciones().getIdsubcapituloUejecucionesParsed()+ " (" + this.getUejecuciones().getIdobraUejecucionesParsed()+")";	
		}
		catch(TorqueException te)
		{
			logger.severe("No se ha podido localizar la unidad de ejecucion. public String getIduejecucionPartesParsed()" );
			te.printStackTrace();
		}
		return FormatUtils.genericParsedStr(uejecucion);
	}	
	public String getFechaPartesParsed()
	{
		return FormatUtils.genericParsedStr(FormatUtils.aaaammdd2ddmmaaaa(this.getFecha(),"-"));
	}	
	public String getDescripcionPartesParsed()
	{
		return FormatUtils.genericParsedStr(this.getDescripcion());
	}	
	public String getObservacionesPartesParsed()
	{
		return FormatUtils.genericParsedStr(this.getObservaciones());
	}
	public String getReferenciaPartesParsed()
	{
		return FormatUtils.genericParsedStr(this.getReferencia());
	}
	public String getHorasPartesParsed()
	{
		return FormatUtils.genericParsedStr(this.getHoras()+"");
	}	
	public String getImportePartesParsed()
	{
		return FormatUtils.genericParsedStr(this.getImporte()+"");
	}	

	public String getDeletePartes()
	{
		return "<a href='#' class='eliminar' id='getDeletePartes" + this.getIdparte() + "'>&#160;&#160;&#160;&#160;</a>";
	}	
	public String getDuplicarPartes()
	{
		return "<a href='#' class='duplicar' id='getDuplicarPartes" + this.getIdparte() + "'>&#160;&#160;&#160;&#160;</a>";
	}		
	public String getEditPartes()
	{
		return "<a href='#' class='edicion' id='getEditPartes" + this.getIdparte() + "'>&#160;&#160;&#160;&#160;</a>";
	}			
}
