
package net.idtoki.aveobras.model;


import java.util.logging.Logger;

import net.zylk.tools.format.FormatUtils;

import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Provincias
    extends net.idtoki.aveobras.model.BaseProvincias
    implements Persistent
{
	private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.model.Provincias");
	
	public String getIdProvinciasParsed()
	{
		return new Integer(this.getIdprovincia()).toString();
	}
	
	public String getNombreProvinciasParsed()
	{
		return FormatUtils.genericParsedStr(this.getNombre()); 
	}	
}
