package net.idtoki.aveobras.helper;

import net.zylk.web.WebUtils;
import net.zylk.web.helper.BaseHelper;
import javax.servlet.http.HttpServletRequest;
import org.apache.torque.TorqueException;
import net.zylk.tools.format.FormatUtils;


import net.idtoki.aveobras.model.IncidenciasPeer;
import net.idtoki.aveobras.model.Incidencias;
import net.idtoki.aveobras.manager.IncidenciasManager;

/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Oct 25 17:01:04 CEST 2006]
 *
 */
public abstract class BaseIncidenciasHelper extends BaseHelper
{
	public static final String COMPLEX_ID_GET_METHOD = "getComplexId";
	private Incidencias obj;
	public static final String IDINCIDENCIA_GET_METHOD_NAME = "getIdincidencia";
	public static final String IDUEJECUCION_GET_METHOD_NAME = "getIduejecucion";
	public static final String IDOPERARIO_GET_METHOD_NAME = "getIdoperario";
	public static final String IDMAQUINARIA_GET_METHOD_NAME = "getIdmaquinaria";
	public static final String IDTIPOINCIDENCIA_GET_METHOD_NAME = "getIdtipoincidencia";
	public static final String FECHA_GET_METHOD_NAME = "getFecha";
	public static final String REFERENCIA_GET_METHOD_NAME = "getReferencia";
	public static final String DESCRIPCION_GET_METHOD_NAME = "getDescripcion";
	public static final String OBSERVACIONES_GET_METHOD_NAME = "getObservaciones";
	public static final String HORAS_GET_METHOD_NAME = "getHoras";
	public static final String IMPORTE_GET_METHOD_NAME = "getImporte";
	public static final String KILOMETROS_GET_METHOD_NAME = "getKilometros";
	public static final String TONELAJE_GET_METHOD_NAME = "getTonelaje";


	public BaseIncidenciasHelper()
	{
		this.obj = new Incidencias();
	}

	public BaseIncidenciasHelper(Incidencias obj)
	{
		this.obj = obj;
	}


	public String getIdincidenciaHTMLAttrs()
	{
		return " name=\"" + getIdincidenciaName() + "\" " +
			   "id=\"" + getIdincidenciaId() + "\" " +
			   "value=\"" + getIdincidenciaValue() + "\" ";
	 }

	public String getIdincidenciaId()
	{
		return getIdincidenciaId(obj);
	}

	private static String getIdincidenciaId(Incidencias o)
	{
		return IncidenciasPeer.IDINCIDENCIA;
	}

	public String getIdincidenciaName()
	{
		return getIdincidenciaName(obj);
	}

	private static String getIdincidenciaName(Incidencias o)
	{
		return IncidenciasPeer.IDINCIDENCIA;
	}

	public String getIdincidenciaValue()
	{
		return getIdincidenciaValue(obj);
	}

	private static String getIdincidenciaValue(Incidencias o)
	{
			return "" + o.getIdincidencia();
		}

	public String getIduejecucionHTMLAttrs()
	{
		return " name=\"" + getIduejecucionName() + "\" " +
			   "id=\"" + getIduejecucionId() + "\" " +
			   "value=\"" + getIduejecucionValue() + "\" ";
	 }

	public String getIduejecucionId()
	{
		return getIduejecucionId(obj);
	}

	private static String getIduejecucionId(Incidencias o)
	{
		return IncidenciasPeer.IDUEJECUCION;
	}

	public String getIduejecucionName()
	{
		return getIduejecucionName(obj);
	}

	private static String getIduejecucionName(Incidencias o)
	{
		return IncidenciasPeer.IDUEJECUCION;
	}

	public String getIduejecucionValue()
	{
		return getIduejecucionValue(obj);
	}

	private static String getIduejecucionValue(Incidencias o)
	{
			return "" + o.getIduejecucion();
		}

	public String getIdoperarioHTMLAttrs()
	{
		return " name=\"" + getIdoperarioName() + "\" " +
			   "id=\"" + getIdoperarioId() + "\" " +
			   "value=\"" + getIdoperarioValue() + "\" ";
	 }

	public String getIdoperarioId()
	{
		return getIdoperarioId(obj);
	}

	private static String getIdoperarioId(Incidencias o)
	{
		return IncidenciasPeer.IDOPERARIO;
	}

	public String getIdoperarioName()
	{
		return getIdoperarioName(obj);
	}

	private static String getIdoperarioName(Incidencias o)
	{
		return IncidenciasPeer.IDOPERARIO;
	}

	public String getIdoperarioValue()
	{
		return getIdoperarioValue(obj);
	}

	private static String getIdoperarioValue(Incidencias o)
	{
			return "" + o.getIdoperario();
		}

	public String getIdmaquinariaHTMLAttrs()
	{
		return " name=\"" + getIdmaquinariaName() + "\" " +
			   "id=\"" + getIdmaquinariaId() + "\" " +
			   "value=\"" + getIdmaquinariaValue() + "\" ";
	 }

	public String getIdmaquinariaId()
	{
		return getIdmaquinariaId(obj);
	}

	private static String getIdmaquinariaId(Incidencias o)
	{
		return IncidenciasPeer.IDMAQUINARIA;
	}

	public String getIdmaquinariaName()
	{
		return getIdmaquinariaName(obj);
	}

	private static String getIdmaquinariaName(Incidencias o)
	{
		return IncidenciasPeer.IDMAQUINARIA;
	}

	public String getIdmaquinariaValue()
	{
		return getIdmaquinariaValue(obj);
	}

	private static String getIdmaquinariaValue(Incidencias o)
	{
			return "" + o.getIdmaquinaria();
		}

	public String getIdtipoincidenciaHTMLAttrs()
	{
		return " name=\"" + getIdtipoincidenciaName() + "\" " +
			   "id=\"" + getIdtipoincidenciaId() + "\" " +
			   "value=\"" + getIdtipoincidenciaValue() + "\" ";
	 }

	public String getIdtipoincidenciaId()
	{
		return getIdtipoincidenciaId(obj);
	}

	private static String getIdtipoincidenciaId(Incidencias o)
	{
		return IncidenciasPeer.IDTIPOINCIDENCIA;
	}

	public String getIdtipoincidenciaName()
	{
		return getIdtipoincidenciaName(obj);
	}

	private static String getIdtipoincidenciaName(Incidencias o)
	{
		return IncidenciasPeer.IDTIPOINCIDENCIA;
	}

	public String getIdtipoincidenciaValue()
	{
		return getIdtipoincidenciaValue(obj);
	}

	private static String getIdtipoincidenciaValue(Incidencias o)
	{
			return "" + o.getIdtipoincidencia();
		}

	public String getFechaHTMLAttrs()
	{
		return " name=\"" + getFechaName() + "\" " +
			   "id=\"" + getFechaId() + "\" " +
			   "value=\"" + getFechaValue() + "\" ";
	 }

	public String getFechaId()
	{
		return getFechaId(obj);
	}

	private static String getFechaId(Incidencias o)
	{
		return IncidenciasPeer.FECHA;
	}

	public String getFechaName()
	{
		return getFechaName(obj);
	}

	private static String getFechaName(Incidencias o)
	{
		return IncidenciasPeer.FECHA;
	}

	public String getFechaValue()
	{
		return getFechaValue(obj);
	}

	private static String getFechaValue(Incidencias o)
	{
			if(o.getFecha() != null)
			return "" + o.getFecha();
		else
			return "";
		}

	public String getReferenciaHTMLAttrs()
	{
		return " name=\"" + getReferenciaName() + "\" " +
			   "id=\"" + getReferenciaId() + "\" " +
			   "value=\"" + getReferenciaValue() + "\" ";
	 }

	public String getReferenciaId()
	{
		return getReferenciaId(obj);
	}

	private static String getReferenciaId(Incidencias o)
	{
		return IncidenciasPeer.REFERENCIA;
	}

	public String getReferenciaName()
	{
		return getReferenciaName(obj);
	}

	private static String getReferenciaName(Incidencias o)
	{
		return IncidenciasPeer.REFERENCIA;
	}

	public String getReferenciaValue()
	{
		return getReferenciaValue(obj);
	}

	private static String getReferenciaValue(Incidencias o)
	{
			if(o.getReferencia() != null)
			return "" + o.getReferencia();
		else
			return "";
		}

	public String getDescripcionHTMLAttrs()
	{
		return " name=\"" + getDescripcionName() + "\" " +
			   "id=\"" + getDescripcionId() + "\" " +
			   "value=\"" + getDescripcionValue() + "\" ";
	 }

	public String getDescripcionId()
	{
		return getDescripcionId(obj);
	}

	private static String getDescripcionId(Incidencias o)
	{
		return IncidenciasPeer.DESCRIPCION;
	}

	public String getDescripcionName()
	{
		return getDescripcionName(obj);
	}

	private static String getDescripcionName(Incidencias o)
	{
		return IncidenciasPeer.DESCRIPCION;
	}

	public String getDescripcionValue()
	{
		return getDescripcionValue(obj);
	}

	private static String getDescripcionValue(Incidencias o)
	{
			if(o.getDescripcion() != null)
			return "" + o.getDescripcion();
		else
			return "";
		}

	public String getObservacionesHTMLAttrs()
	{
		return " name=\"" + getObservacionesName() + "\" " +
			   "id=\"" + getObservacionesId() + "\" " +
			   "value=\"" + getObservacionesValue() + "\" ";
	 }

	public String getObservacionesId()
	{
		return getObservacionesId(obj);
	}

	private static String getObservacionesId(Incidencias o)
	{
		return IncidenciasPeer.OBSERVACIONES;
	}

	public String getObservacionesName()
	{
		return getObservacionesName(obj);
	}

	private static String getObservacionesName(Incidencias o)
	{
		return IncidenciasPeer.OBSERVACIONES;
	}

	public String getObservacionesValue()
	{
		return getObservacionesValue(obj);
	}

	private static String getObservacionesValue(Incidencias o)
	{
			if(o.getObservaciones() != null)
			return "" + o.getObservaciones();
		else
			return "";
		}

	public String getHorasHTMLAttrs()
	{
		return " name=\"" + getHorasName() + "\" " +
			   "id=\"" + getHorasId() + "\" " +
			   "value=\"" + getHorasValue() + "\" ";
	 }

	public String getHorasId()
	{
		return getHorasId(obj);
	}

	private static String getHorasId(Incidencias o)
	{
		return IncidenciasPeer.HORAS;
	}

	public String getHorasName()
	{
		return getHorasName(obj);
	}

	private static String getHorasName(Incidencias o)
	{
		return IncidenciasPeer.HORAS;
	}

	public String getHorasValue()
	{
		return getHorasValue(obj);
	}

	private static String getHorasValue(Incidencias o)
	{
			return "" + o.getHoras();
		}

	public String getImporteHTMLAttrs()
	{
		return " name=\"" + getImporteName() + "\" " +
			   "id=\"" + getImporteId() + "\" " +
			   "value=\"" + getImporteValue() + "\" ";
	 }

	public String getImporteId()
	{
		return getImporteId(obj);
	}

	private static String getImporteId(Incidencias o)
	{
		return IncidenciasPeer.IMPORTE;
	}

	public String getImporteName()
	{
		return getImporteName(obj);
	}

	private static String getImporteName(Incidencias o)
	{
		return IncidenciasPeer.IMPORTE;
	}

	public String getImporteValue()
	{
		return getImporteValue(obj);
	}

	private static String getImporteValue(Incidencias o)
	{
			return "" + o.getImporte();
		}

	public String getKilometrosHTMLAttrs()
	{
		return " name=\"" + getKilometrosName() + "\" " +
			   "id=\"" + getKilometrosId() + "\" " +
			   "value=\"" + getKilometrosValue() + "\" ";
	 }

	public String getKilometrosId()
	{
		return getKilometrosId(obj);
	}

	private static String getKilometrosId(Incidencias o)
	{
		return IncidenciasPeer.KILOMETROS;
	}

	public String getKilometrosName()
	{
		return getKilometrosName(obj);
	}

	private static String getKilometrosName(Incidencias o)
	{
		return IncidenciasPeer.KILOMETROS;
	}

	public String getKilometrosValue()
	{
		return getKilometrosValue(obj);
	}

	private static String getKilometrosValue(Incidencias o)
	{
			return "" + o.getKilometros();
		}

	public String getTonelajeHTMLAttrs()
	{
		return " name=\"" + getTonelajeName() + "\" " +
			   "id=\"" + getTonelajeId() + "\" " +
			   "value=\"" + getTonelajeValue() + "\" ";
	 }

	public String getTonelajeId()
	{
		return getTonelajeId(obj);
	}

	private static String getTonelajeId(Incidencias o)
	{
		return IncidenciasPeer.TONELAJE;
	}

	public String getTonelajeName()
	{
		return getTonelajeName(obj);
	}

	private static String getTonelajeName(Incidencias o)
	{
		return IncidenciasPeer.TONELAJE;
	}

	public String getTonelajeValue()
	{
		return getTonelajeValue(obj);
	}

	private static String getTonelajeValue(Incidencias o)
	{
			return "" + o.getTonelaje();
		}

	public static Incidencias getIncidencias(HttpServletRequest req) throws TorqueException
	{
										
		int id_Idincidencia = WebUtils.getintParam(req, getIdincidenciaName(new Incidencias()));

	
		Incidencias o = new Incidencias();
		if((id_Idincidencia >= 0)) // no es nuevo y lo fijamos en el objeto
		{
			o = IncidenciasManager.getIncidencias(id_Idincidencia);
		}
		return o;
	}

	public static Incidencias createObj(HttpServletRequest req) throws TorqueException
	{
		Incidencias o =  BaseIncidenciasHelper.getIncidencias(req);
			 o.setIdincidencia(WebUtils.getintParam(req, getIdincidenciaName(o)));
		
			 		o.setIduejecucion(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIduejecucionName(o)))));
		
			 		o.setIdoperario(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIdoperarioName(o)))));
		
			 		o.setIdmaquinaria(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIdmaquinariaName(o)))));
		
			 		o.setIdtipoincidencia(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIdtipoincidenciaName(o)))));
		
			 o.setFecha(WebUtils.getStringParam(req, getFechaName(o)));
		
			 o.setReferencia(WebUtils.getStringParam(req, getReferenciaName(o)));
		
			 o.setDescripcion(WebUtils.getStringParam(req, getDescripcionName(o)));
		
			 o.setObservaciones(WebUtils.getStringParam(req, getObservacionesName(o)));
		
			 o.setHoras(WebUtils.getdoubleParam(req, getHorasName(o)));
		
			 o.setImporte(WebUtils.getdoubleParam(req, getImporteName(o)));
		
			 o.setKilometros(WebUtils.getdoubleParam(req, getKilometrosName(o)));
		
			 o.setTonelaje(WebUtils.getdoubleParam(req, getTonelajeName(o)));
		
			return o;
	}
}
