package net.idtoki.aveobras.helper;

import net.zylk.web.WebUtils;
import net.zylk.web.helper.BaseHelper;
import javax.servlet.http.HttpServletRequest;
import org.apache.torque.TorqueException;
import net.zylk.tools.format.FormatUtils;


import net.idtoki.aveobras.model.ObrasPeer;
import net.idtoki.aveobras.model.Obras;
import net.idtoki.aveobras.manager.ObrasManager;

/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Oct 25 17:01:04 CEST 2006]
 *
 */
public abstract class BaseObrasHelper extends BaseHelper
{
	public static final String COMPLEX_ID_GET_METHOD = "getComplexId";
	private Obras obj;
	public static final String IDOBRA_GET_METHOD_NAME = "getIdobra";
	public static final String IDCLIENTE_GET_METHOD_NAME = "getIdcliente";
	public static final String NUMEROCONTRATO_GET_METHOD_NAME = "getNumerocontrato";
	public static final String REFERENCIA_GET_METHOD_NAME = "getReferencia";
	public static final String NOMBRE_GET_METHOD_NAME = "getNombre";
	public static final String IDLOCALIDAD_GET_METHOD_NAME = "getIdlocalidad";
	public static final String CALLE_GET_METHOD_NAME = "getCalle";
	public static final String CP_GET_METHOD_NAME = "getCp";
	public static final String FECHAALTA_GET_METHOD_NAME = "getFechaalta";
	public static final String FECHACOMIENZO_GET_METHOD_NAME = "getFechacomienzo";
	public static final String FECHAFIN_GET_METHOD_NAME = "getFechafin";
	public static final String JORNADAS_GET_METHOD_NAME = "getJornadas";
	public static final String OBSERVACIONES_GET_METHOD_NAME = "getObservaciones";


	public BaseObrasHelper()
	{
		this.obj = new Obras();
	}

	public BaseObrasHelper(Obras obj)
	{
		this.obj = obj;
	}


	public String getIdobraHTMLAttrs()
	{
		return " name=\"" + getIdobraName() + "\" " +
			   "id=\"" + getIdobraId() + "\" " +
			   "value=\"" + getIdobraValue() + "\" ";
	 }

	public String getIdobraId()
	{
		return getIdobraId(obj);
	}

	private static String getIdobraId(Obras o)
	{
		return ObrasPeer.IDOBRA;
	}

	public String getIdobraName()
	{
		return getIdobraName(obj);
	}

	private static String getIdobraName(Obras o)
	{
		return ObrasPeer.IDOBRA;
	}

	public String getIdobraValue()
	{
		return getIdobraValue(obj);
	}

	private static String getIdobraValue(Obras o)
	{
			return "" + o.getIdobra();
		}

	public String getIdclienteHTMLAttrs()
	{
		return " name=\"" + getIdclienteName() + "\" " +
			   "id=\"" + getIdclienteId() + "\" " +
			   "value=\"" + getIdclienteValue() + "\" ";
	 }

	public String getIdclienteId()
	{
		return getIdclienteId(obj);
	}

	private static String getIdclienteId(Obras o)
	{
		return ObrasPeer.IDCLIENTE;
	}

	public String getIdclienteName()
	{
		return getIdclienteName(obj);
	}

	private static String getIdclienteName(Obras o)
	{
		return ObrasPeer.IDCLIENTE;
	}

	public String getIdclienteValue()
	{
		return getIdclienteValue(obj);
	}

	private static String getIdclienteValue(Obras o)
	{
			return "" + o.getIdcliente();
		}

	public String getNumerocontratoHTMLAttrs()
	{
		return " name=\"" + getNumerocontratoName() + "\" " +
			   "id=\"" + getNumerocontratoId() + "\" " +
			   "value=\"" + getNumerocontratoValue() + "\" ";
	 }

	public String getNumerocontratoId()
	{
		return getNumerocontratoId(obj);
	}

	private static String getNumerocontratoId(Obras o)
	{
		return ObrasPeer.NUMEROCONTRATO;
	}

	public String getNumerocontratoName()
	{
		return getNumerocontratoName(obj);
	}

	private static String getNumerocontratoName(Obras o)
	{
		return ObrasPeer.NUMEROCONTRATO;
	}

	public String getNumerocontratoValue()
	{
		return getNumerocontratoValue(obj);
	}

	private static String getNumerocontratoValue(Obras o)
	{
			if(o.getNumerocontrato() != null)
			return "" + o.getNumerocontrato();
		else
			return "";
		}

	public String getReferenciaHTMLAttrs()
	{
		return " name=\"" + getReferenciaName() + "\" " +
			   "id=\"" + getReferenciaId() + "\" " +
			   "value=\"" + getReferenciaValue() + "\" ";
	 }

	public String getReferenciaId()
	{
		return getReferenciaId(obj);
	}

	private static String getReferenciaId(Obras o)
	{
		return ObrasPeer.REFERENCIA;
	}

	public String getReferenciaName()
	{
		return getReferenciaName(obj);
	}

	private static String getReferenciaName(Obras o)
	{
		return ObrasPeer.REFERENCIA;
	}

	public String getReferenciaValue()
	{
		return getReferenciaValue(obj);
	}

	private static String getReferenciaValue(Obras o)
	{
			if(o.getReferencia() != null)
			return "" + o.getReferencia();
		else
			return "";
		}

	public String getNombreHTMLAttrs()
	{
		return " name=\"" + getNombreName() + "\" " +
			   "id=\"" + getNombreId() + "\" " +
			   "value=\"" + getNombreValue() + "\" ";
	 }

	public String getNombreId()
	{
		return getNombreId(obj);
	}

	private static String getNombreId(Obras o)
	{
		return ObrasPeer.NOMBRE;
	}

	public String getNombreName()
	{
		return getNombreName(obj);
	}

	private static String getNombreName(Obras o)
	{
		return ObrasPeer.NOMBRE;
	}

	public String getNombreValue()
	{
		return getNombreValue(obj);
	}

	private static String getNombreValue(Obras o)
	{
			if(o.getNombre() != null)
			return "" + o.getNombre();
		else
			return "";
		}

	public String getIdlocalidadHTMLAttrs()
	{
		return " name=\"" + getIdlocalidadName() + "\" " +
			   "id=\"" + getIdlocalidadId() + "\" " +
			   "value=\"" + getIdlocalidadValue() + "\" ";
	 }

	public String getIdlocalidadId()
	{
		return getIdlocalidadId(obj);
	}

	private static String getIdlocalidadId(Obras o)
	{
		return ObrasPeer.IDLOCALIDAD;
	}

	public String getIdlocalidadName()
	{
		return getIdlocalidadName(obj);
	}

	private static String getIdlocalidadName(Obras o)
	{
		return ObrasPeer.IDLOCALIDAD;
	}

	public String getIdlocalidadValue()
	{
		return getIdlocalidadValue(obj);
	}

	private static String getIdlocalidadValue(Obras o)
	{
			return "" + o.getIdlocalidad();
		}

	public String getCalleHTMLAttrs()
	{
		return " name=\"" + getCalleName() + "\" " +
			   "id=\"" + getCalleId() + "\" " +
			   "value=\"" + getCalleValue() + "\" ";
	 }

	public String getCalleId()
	{
		return getCalleId(obj);
	}

	private static String getCalleId(Obras o)
	{
		return ObrasPeer.CALLE;
	}

	public String getCalleName()
	{
		return getCalleName(obj);
	}

	private static String getCalleName(Obras o)
	{
		return ObrasPeer.CALLE;
	}

	public String getCalleValue()
	{
		return getCalleValue(obj);
	}

	private static String getCalleValue(Obras o)
	{
			if(o.getCalle() != null)
			return "" + o.getCalle();
		else
			return "";
		}

	public String getCpHTMLAttrs()
	{
		return " name=\"" + getCpName() + "\" " +
			   "id=\"" + getCpId() + "\" " +
			   "value=\"" + getCpValue() + "\" ";
	 }

	public String getCpId()
	{
		return getCpId(obj);
	}

	private static String getCpId(Obras o)
	{
		return ObrasPeer.CP;
	}

	public String getCpName()
	{
		return getCpName(obj);
	}

	private static String getCpName(Obras o)
	{
		return ObrasPeer.CP;
	}

	public String getCpValue()
	{
		return getCpValue(obj);
	}

	private static String getCpValue(Obras o)
	{
			if(o.getCp() != null)
			return "" + o.getCp();
		else
			return "";
		}

	public String getFechaaltaHTMLAttrs()
	{
		return " name=\"" + getFechaaltaName() + "\" " +
			   "id=\"" + getFechaaltaId() + "\" " +
			   "value=\"" + getFechaaltaValue() + "\" ";
	 }

	public String getFechaaltaId()
	{
		return getFechaaltaId(obj);
	}

	private static String getFechaaltaId(Obras o)
	{
		return ObrasPeer.FECHAALTA;
	}

	public String getFechaaltaName()
	{
		return getFechaaltaName(obj);
	}

	private static String getFechaaltaName(Obras o)
	{
		return ObrasPeer.FECHAALTA;
	}

	public String getFechaaltaValue()
	{
		return getFechaaltaValue(obj);
	}

	private static String getFechaaltaValue(Obras o)
	{
			if(o.getFechaalta() != null)
			return "" + o.getFechaalta();
		else
			return "";
		}

	public String getFechacomienzoHTMLAttrs()
	{
		return " name=\"" + getFechacomienzoName() + "\" " +
			   "id=\"" + getFechacomienzoId() + "\" " +
			   "value=\"" + getFechacomienzoValue() + "\" ";
	 }

	public String getFechacomienzoId()
	{
		return getFechacomienzoId(obj);
	}

	private static String getFechacomienzoId(Obras o)
	{
		return ObrasPeer.FECHACOMIENZO;
	}

	public String getFechacomienzoName()
	{
		return getFechacomienzoName(obj);
	}

	private static String getFechacomienzoName(Obras o)
	{
		return ObrasPeer.FECHACOMIENZO;
	}

	public String getFechacomienzoValue()
	{
		return getFechacomienzoValue(obj);
	}

	private static String getFechacomienzoValue(Obras o)
	{
			if(o.getFechacomienzo() != null)
			return "" + o.getFechacomienzo();
		else
			return "";
		}

	public String getFechafinHTMLAttrs()
	{
		return " name=\"" + getFechafinName() + "\" " +
			   "id=\"" + getFechafinId() + "\" " +
			   "value=\"" + getFechafinValue() + "\" ";
	 }

	public String getFechafinId()
	{
		return getFechafinId(obj);
	}

	private static String getFechafinId(Obras o)
	{
		return ObrasPeer.FECHAFIN;
	}

	public String getFechafinName()
	{
		return getFechafinName(obj);
	}

	private static String getFechafinName(Obras o)
	{
		return ObrasPeer.FECHAFIN;
	}

	public String getFechafinValue()
	{
		return getFechafinValue(obj);
	}

	private static String getFechafinValue(Obras o)
	{
			if(o.getFechafin() != null)
			return "" + o.getFechafin();
		else
			return "";
		}

	public String getJornadasHTMLAttrs()
	{
		return " name=\"" + getJornadasName() + "\" " +
			   "id=\"" + getJornadasId() + "\" " +
			   "value=\"" + getJornadasValue() + "\" ";
	 }

	public String getJornadasId()
	{
		return getJornadasId(obj);
	}

	private static String getJornadasId(Obras o)
	{
		return ObrasPeer.JORNADAS;
	}

	public String getJornadasName()
	{
		return getJornadasName(obj);
	}

	private static String getJornadasName(Obras o)
	{
		return ObrasPeer.JORNADAS;
	}

	public String getJornadasValue()
	{
		return getJornadasValue(obj);
	}

	private static String getJornadasValue(Obras o)
	{
			return "" + o.getJornadas();
		}

	public String getObservacionesHTMLAttrs()
	{
		return " name=\"" + getObservacionesName() + "\" " +
			   "id=\"" + getObservacionesId() + "\" " +
			   "value=\"" + getObservacionesValue() + "\" ";
	 }

	public String getObservacionesId()
	{
		return getObservacionesId(obj);
	}

	private static String getObservacionesId(Obras o)
	{
		return ObrasPeer.OBSERVACIONES;
	}

	public String getObservacionesName()
	{
		return getObservacionesName(obj);
	}

	private static String getObservacionesName(Obras o)
	{
		return ObrasPeer.OBSERVACIONES;
	}

	public String getObservacionesValue()
	{
		return getObservacionesValue(obj);
	}

	private static String getObservacionesValue(Obras o)
	{
			if(o.getObservaciones() != null)
			return "" + o.getObservaciones();
		else
			return "";
		}

	public static Obras getObras(HttpServletRequest req) throws TorqueException
	{
										
		int id_Idobra = WebUtils.getintParam(req, getIdobraName(new Obras()));

	
		Obras o = new Obras();
		if((id_Idobra >= 0)) // no es nuevo y lo fijamos en el objeto
		{
			o = ObrasManager.getObras(id_Idobra);
		}
		return o;
	}

	public static Obras createObj(HttpServletRequest req) throws TorqueException
	{
		Obras o =  BaseObrasHelper.getObras(req);
			 o.setIdobra(WebUtils.getintParam(req, getIdobraName(o)));
		
			 		o.setIdcliente(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIdclienteName(o)))));
		
			 o.setNumerocontrato(WebUtils.getStringParam(req, getNumerocontratoName(o)));
		
			 o.setReferencia(WebUtils.getStringParam(req, getReferenciaName(o)));
		
			 o.setNombre(WebUtils.getStringParam(req, getNombreName(o)));
		
			 		o.setIdlocalidad(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIdlocalidadName(o)))));
		
			 o.setCalle(WebUtils.getStringParam(req, getCalleName(o)));
		
			 o.setCp(WebUtils.getStringParam(req, getCpName(o)));
		
			 o.setFechaalta(WebUtils.getStringParam(req, getFechaaltaName(o)));
		
			 o.setFechacomienzo(WebUtils.getStringParam(req, getFechacomienzoName(o)));
		
			 o.setFechafin(WebUtils.getStringParam(req, getFechafinName(o)));
		
			 o.setJornadas(WebUtils.getintParam(req, getJornadasName(o)));
		
			 o.setObservaciones(WebUtils.getStringParam(req, getObservacionesName(o)));
		
			return o;
	}
}
