package net.idtoki.aveobras.helper;

import net.zylk.web.WebUtils;
import net.zylk.web.helper.BaseHelper;
import javax.servlet.http.HttpServletRequest;
import org.apache.torque.TorqueException;
import net.zylk.tools.format.FormatUtils;


import net.idtoki.aveobras.model.OperariosPeer;
import net.idtoki.aveobras.model.Operarios;
import net.idtoki.aveobras.manager.OperariosManager;

/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Oct 25 17:01:04 CEST 2006]
 *
 */
public abstract class BaseOperariosHelper extends BaseHelper
{
	public static final String COMPLEX_ID_GET_METHOD = "getComplexId";
	private Operarios obj;
	public static final String IDOPERARIO_GET_METHOD_NAME = "getIdoperario";
	public static final String IDCATEGORIA_GET_METHOD_NAME = "getIdcategoria";
	public static final String REFERENCIA_GET_METHOD_NAME = "getReferencia";
	public static final String NIF_GET_METHOD_NAME = "getNif";
	public static final String NOMBRE_GET_METHOD_NAME = "getNombre";
	public static final String APELLIDOUNO_GET_METHOD_NAME = "getApellidouno";
	public static final String APELLIDODOS_GET_METHOD_NAME = "getApellidodos";
	public static final String FECHAALTA_GET_METHOD_NAME = "getFechaalta";
	public static final String FECHABAJA_GET_METHOD_NAME = "getFechabaja";
	public static final String NUMEROSS_GET_METHOD_NAME = "getNumeross";
	public static final String DIRECCION_GET_METHOD_NAME = "getDireccion";
	public static final String CP_GET_METHOD_NAME = "getCp";
	public static final String IDLOCALIDAD_GET_METHOD_NAME = "getIdlocalidad";
	public static final String TELEFONO_GET_METHOD_NAME = "getTelefono";
	public static final String MOVIL_GET_METHOD_NAME = "getMovil";
	public static final String EMAIL_GET_METHOD_NAME = "getEmail";
	public static final String COSTE_GET_METHOD_NAME = "getCoste";
	public static final String EXTERNO_GET_METHOD_NAME = "getExterno";
	public static final String OBSERVACIONES_GET_METHOD_NAME = "getObservaciones";


	public BaseOperariosHelper()
	{
		this.obj = new Operarios();
	}

	public BaseOperariosHelper(Operarios obj)
	{
		this.obj = obj;
	}


	public String getIdoperarioHTMLAttrs()
	{
		return " name=\"" + getIdoperarioName() + "\" " +
			   "id=\"" + getIdoperarioId() + "\" " +
			   "value=\"" + getIdoperarioValue() + "\" ";
	 }

	public String getIdoperarioId()
	{
		return getIdoperarioId(obj);
	}

	private static String getIdoperarioId(Operarios o)
	{
		return OperariosPeer.IDOPERARIO;
	}

	public String getIdoperarioName()
	{
		return getIdoperarioName(obj);
	}

	private static String getIdoperarioName(Operarios o)
	{
		return OperariosPeer.IDOPERARIO;
	}

	public String getIdoperarioValue()
	{
		return getIdoperarioValue(obj);
	}

	private static String getIdoperarioValue(Operarios o)
	{
			return "" + o.getIdoperario();
		}

	public String getIdcategoriaHTMLAttrs()
	{
		return " name=\"" + getIdcategoriaName() + "\" " +
			   "id=\"" + getIdcategoriaId() + "\" " +
			   "value=\"" + getIdcategoriaValue() + "\" ";
	 }

	public String getIdcategoriaId()
	{
		return getIdcategoriaId(obj);
	}

	private static String getIdcategoriaId(Operarios o)
	{
		return OperariosPeer.IDCATEGORIA;
	}

	public String getIdcategoriaName()
	{
		return getIdcategoriaName(obj);
	}

	private static String getIdcategoriaName(Operarios o)
	{
		return OperariosPeer.IDCATEGORIA;
	}

	public String getIdcategoriaValue()
	{
		return getIdcategoriaValue(obj);
	}

	private static String getIdcategoriaValue(Operarios o)
	{
			return "" + o.getIdcategoria();
		}

	public String getReferenciaHTMLAttrs()
	{
		return " name=\"" + getReferenciaName() + "\" " +
			   "id=\"" + getReferenciaId() + "\" " +
			   "value=\"" + getReferenciaValue() + "\" ";
	 }

	public String getReferenciaId()
	{
		return getReferenciaId(obj);
	}

	private static String getReferenciaId(Operarios o)
	{
		return OperariosPeer.REFERENCIA;
	}

	public String getReferenciaName()
	{
		return getReferenciaName(obj);
	}

	private static String getReferenciaName(Operarios o)
	{
		return OperariosPeer.REFERENCIA;
	}

	public String getReferenciaValue()
	{
		return getReferenciaValue(obj);
	}

	private static String getReferenciaValue(Operarios o)
	{
			if(o.getReferencia() != null)
			return "" + o.getReferencia();
		else
			return "";
		}

	public String getNifHTMLAttrs()
	{
		return " name=\"" + getNifName() + "\" " +
			   "id=\"" + getNifId() + "\" " +
			   "value=\"" + getNifValue() + "\" ";
	 }

	public String getNifId()
	{
		return getNifId(obj);
	}

	private static String getNifId(Operarios o)
	{
		return OperariosPeer.NIF;
	}

	public String getNifName()
	{
		return getNifName(obj);
	}

	private static String getNifName(Operarios o)
	{
		return OperariosPeer.NIF;
	}

	public String getNifValue()
	{
		return getNifValue(obj);
	}

	private static String getNifValue(Operarios o)
	{
			if(o.getNif() != null)
			return "" + o.getNif();
		else
			return "";
		}

	public String getNombreHTMLAttrs()
	{
		return " name=\"" + getNombreName() + "\" " +
			   "id=\"" + getNombreId() + "\" " +
			   "value=\"" + getNombreValue() + "\" ";
	 }

	public String getNombreId()
	{
		return getNombreId(obj);
	}

	private static String getNombreId(Operarios o)
	{
		return OperariosPeer.NOMBRE;
	}

	public String getNombreName()
	{
		return getNombreName(obj);
	}

	private static String getNombreName(Operarios o)
	{
		return OperariosPeer.NOMBRE;
	}

	public String getNombreValue()
	{
		return getNombreValue(obj);
	}

	private static String getNombreValue(Operarios o)
	{
			if(o.getNombre() != null)
			return "" + o.getNombre();
		else
			return "";
		}

	public String getApellidounoHTMLAttrs()
	{
		return " name=\"" + getApellidounoName() + "\" " +
			   "id=\"" + getApellidounoId() + "\" " +
			   "value=\"" + getApellidounoValue() + "\" ";
	 }

	public String getApellidounoId()
	{
		return getApellidounoId(obj);
	}

	private static String getApellidounoId(Operarios o)
	{
		return OperariosPeer.APELLIDOUNO;
	}

	public String getApellidounoName()
	{
		return getApellidounoName(obj);
	}

	private static String getApellidounoName(Operarios o)
	{
		return OperariosPeer.APELLIDOUNO;
	}

	public String getApellidounoValue()
	{
		return getApellidounoValue(obj);
	}

	private static String getApellidounoValue(Operarios o)
	{
			if(o.getApellidouno() != null)
			return "" + o.getApellidouno();
		else
			return "";
		}

	public String getApellidodosHTMLAttrs()
	{
		return " name=\"" + getApellidodosName() + "\" " +
			   "id=\"" + getApellidodosId() + "\" " +
			   "value=\"" + getApellidodosValue() + "\" ";
	 }

	public String getApellidodosId()
	{
		return getApellidodosId(obj);
	}

	private static String getApellidodosId(Operarios o)
	{
		return OperariosPeer.APELLIDODOS;
	}

	public String getApellidodosName()
	{
		return getApellidodosName(obj);
	}

	private static String getApellidodosName(Operarios o)
	{
		return OperariosPeer.APELLIDODOS;
	}

	public String getApellidodosValue()
	{
		return getApellidodosValue(obj);
	}

	private static String getApellidodosValue(Operarios o)
	{
			if(o.getApellidodos() != null)
			return "" + o.getApellidodos();
		else
			return "";
		}

	public String getFechaaltaHTMLAttrs()
	{
		return " name=\"" + getFechaaltaName() + "\" " +
			   "id=\"" + getFechaaltaId() + "\" " +
			   "value=\"" + getFechaaltaValue() + "\" ";
	 }

	public String getFechaaltaId()
	{
		return getFechaaltaId(obj);
	}

	private static String getFechaaltaId(Operarios o)
	{
		return OperariosPeer.FECHAALTA;
	}

	public String getFechaaltaName()
	{
		return getFechaaltaName(obj);
	}

	private static String getFechaaltaName(Operarios o)
	{
		return OperariosPeer.FECHAALTA;
	}

	public String getFechaaltaValue()
	{
		return getFechaaltaValue(obj);
	}

	private static String getFechaaltaValue(Operarios o)
	{
			if(o.getFechaalta() != null)
			return "" + o.getFechaalta();
		else
			return "";
		}

	public String getFechabajaHTMLAttrs()
	{
		return " name=\"" + getFechabajaName() + "\" " +
			   "id=\"" + getFechabajaId() + "\" " +
			   "value=\"" + getFechabajaValue() + "\" ";
	 }

	public String getFechabajaId()
	{
		return getFechabajaId(obj);
	}

	private static String getFechabajaId(Operarios o)
	{
		return OperariosPeer.FECHABAJA;
	}

	public String getFechabajaName()
	{
		return getFechabajaName(obj);
	}

	private static String getFechabajaName(Operarios o)
	{
		return OperariosPeer.FECHABAJA;
	}

	public String getFechabajaValue()
	{
		return getFechabajaValue(obj);
	}

	private static String getFechabajaValue(Operarios o)
	{
			if(o.getFechabaja() != null)
			return "" + o.getFechabaja();
		else
			return "";
		}

	public String getNumerossHTMLAttrs()
	{
		return " name=\"" + getNumerossName() + "\" " +
			   "id=\"" + getNumerossId() + "\" " +
			   "value=\"" + getNumerossValue() + "\" ";
	 }

	public String getNumerossId()
	{
		return getNumerossId(obj);
	}

	private static String getNumerossId(Operarios o)
	{
		return OperariosPeer.NUMEROSS;
	}

	public String getNumerossName()
	{
		return getNumerossName(obj);
	}

	private static String getNumerossName(Operarios o)
	{
		return OperariosPeer.NUMEROSS;
	}

	public String getNumerossValue()
	{
		return getNumerossValue(obj);
	}

	private static String getNumerossValue(Operarios o)
	{
			if(o.getNumeross() != null)
			return "" + o.getNumeross();
		else
			return "";
		}

	public String getDireccionHTMLAttrs()
	{
		return " name=\"" + getDireccionName() + "\" " +
			   "id=\"" + getDireccionId() + "\" " +
			   "value=\"" + getDireccionValue() + "\" ";
	 }

	public String getDireccionId()
	{
		return getDireccionId(obj);
	}

	private static String getDireccionId(Operarios o)
	{
		return OperariosPeer.DIRECCION;
	}

	public String getDireccionName()
	{
		return getDireccionName(obj);
	}

	private static String getDireccionName(Operarios o)
	{
		return OperariosPeer.DIRECCION;
	}

	public String getDireccionValue()
	{
		return getDireccionValue(obj);
	}

	private static String getDireccionValue(Operarios o)
	{
			if(o.getDireccion() != null)
			return "" + o.getDireccion();
		else
			return "";
		}

	public String getCpHTMLAttrs()
	{
		return " name=\"" + getCpName() + "\" " +
			   "id=\"" + getCpId() + "\" " +
			   "value=\"" + getCpValue() + "\" ";
	 }

	public String getCpId()
	{
		return getCpId(obj);
	}

	private static String getCpId(Operarios o)
	{
		return OperariosPeer.CP;
	}

	public String getCpName()
	{
		return getCpName(obj);
	}

	private static String getCpName(Operarios o)
	{
		return OperariosPeer.CP;
	}

	public String getCpValue()
	{
		return getCpValue(obj);
	}

	private static String getCpValue(Operarios o)
	{
			if(o.getCp() != null)
			return "" + o.getCp();
		else
			return "";
		}

	public String getIdlocalidadHTMLAttrs()
	{
		return " name=\"" + getIdlocalidadName() + "\" " +
			   "id=\"" + getIdlocalidadId() + "\" " +
			   "value=\"" + getIdlocalidadValue() + "\" ";
	 }

	public String getIdlocalidadId()
	{
		return getIdlocalidadId(obj);
	}

	private static String getIdlocalidadId(Operarios o)
	{
		return OperariosPeer.IDLOCALIDAD;
	}

	public String getIdlocalidadName()
	{
		return getIdlocalidadName(obj);
	}

	private static String getIdlocalidadName(Operarios o)
	{
		return OperariosPeer.IDLOCALIDAD;
	}

	public String getIdlocalidadValue()
	{
		return getIdlocalidadValue(obj);
	}

	private static String getIdlocalidadValue(Operarios o)
	{
			return "" + o.getIdlocalidad();
		}

	public String getTelefonoHTMLAttrs()
	{
		return " name=\"" + getTelefonoName() + "\" " +
			   "id=\"" + getTelefonoId() + "\" " +
			   "value=\"" + getTelefonoValue() + "\" ";
	 }

	public String getTelefonoId()
	{
		return getTelefonoId(obj);
	}

	private static String getTelefonoId(Operarios o)
	{
		return OperariosPeer.TELEFONO;
	}

	public String getTelefonoName()
	{
		return getTelefonoName(obj);
	}

	private static String getTelefonoName(Operarios o)
	{
		return OperariosPeer.TELEFONO;
	}

	public String getTelefonoValue()
	{
		return getTelefonoValue(obj);
	}

	private static String getTelefonoValue(Operarios o)
	{
			if(o.getTelefono() != null)
			return "" + o.getTelefono();
		else
			return "";
		}

	public String getMovilHTMLAttrs()
	{
		return " name=\"" + getMovilName() + "\" " +
			   "id=\"" + getMovilId() + "\" " +
			   "value=\"" + getMovilValue() + "\" ";
	 }

	public String getMovilId()
	{
		return getMovilId(obj);
	}

	private static String getMovilId(Operarios o)
	{
		return OperariosPeer.MOVIL;
	}

	public String getMovilName()
	{
		return getMovilName(obj);
	}

	private static String getMovilName(Operarios o)
	{
		return OperariosPeer.MOVIL;
	}

	public String getMovilValue()
	{
		return getMovilValue(obj);
	}

	private static String getMovilValue(Operarios o)
	{
			if(o.getMovil() != null)
			return "" + o.getMovil();
		else
			return "";
		}

	public String getEmailHTMLAttrs()
	{
		return " name=\"" + getEmailName() + "\" " +
			   "id=\"" + getEmailId() + "\" " +
			   "value=\"" + getEmailValue() + "\" ";
	 }

	public String getEmailId()
	{
		return getEmailId(obj);
	}

	private static String getEmailId(Operarios o)
	{
		return OperariosPeer.EMAIL;
	}

	public String getEmailName()
	{
		return getEmailName(obj);
	}

	private static String getEmailName(Operarios o)
	{
		return OperariosPeer.EMAIL;
	}

	public String getEmailValue()
	{
		return getEmailValue(obj);
	}

	private static String getEmailValue(Operarios o)
	{
			if(o.getEmail() != null)
			return "" + o.getEmail();
		else
			return "";
		}

	public String getCosteHTMLAttrs()
	{
		return " name=\"" + getCosteName() + "\" " +
			   "id=\"" + getCosteId() + "\" " +
			   "value=\"" + getCosteValue() + "\" ";
	 }

	public String getCosteId()
	{
		return getCosteId(obj);
	}

	private static String getCosteId(Operarios o)
	{
		return OperariosPeer.COSTE;
	}

	public String getCosteName()
	{
		return getCosteName(obj);
	}

	private static String getCosteName(Operarios o)
	{
		return OperariosPeer.COSTE;
	}

	public String getCosteValue()
	{
		return getCosteValue(obj);
	}

	private static String getCosteValue(Operarios o)
	{
			return "" + o.getCoste();
		}

	public String getExternoHTMLAttrs()
	{
		return " name=\"" + getExternoName() + "\" " +
			   "id=\"" + getExternoId() + "\" " +
			   "value=\"" + getExternoValue() + "\" ";
	 }

	public String getExternoId()
	{
		return getExternoId(obj);
	}

	private static String getExternoId(Operarios o)
	{
		return OperariosPeer.EXTERNO;
	}

	public String getExternoName()
	{
		return getExternoName(obj);
	}

	private static String getExternoName(Operarios o)
	{
		return OperariosPeer.EXTERNO;
	}

	public String getExternoValue()
	{
		return getExternoValue(obj);
	}

	private static String getExternoValue(Operarios o)
	{
			return "" + o.getExterno();
		}

	public String getObservacionesHTMLAttrs()
	{
		return " name=\"" + getObservacionesName() + "\" " +
			   "id=\"" + getObservacionesId() + "\" " +
			   "value=\"" + getObservacionesValue() + "\" ";
	 }

	public String getObservacionesId()
	{
		return getObservacionesId(obj);
	}

	private static String getObservacionesId(Operarios o)
	{
		return OperariosPeer.OBSERVACIONES;
	}

	public String getObservacionesName()
	{
		return getObservacionesName(obj);
	}

	private static String getObservacionesName(Operarios o)
	{
		return OperariosPeer.OBSERVACIONES;
	}

	public String getObservacionesValue()
	{
		return getObservacionesValue(obj);
	}

	private static String getObservacionesValue(Operarios o)
	{
			if(o.getObservaciones() != null)
			return "" + o.getObservaciones();
		else
			return "";
		}

	public static Operarios getOperarios(HttpServletRequest req) throws TorqueException
	{
										
		int id_Idoperario = WebUtils.getintParam(req, getIdoperarioName(new Operarios()));

	
		Operarios o = new Operarios();
		if((id_Idoperario >= 0)) // no es nuevo y lo fijamos en el objeto
		{
			o = OperariosManager.getOperarios(id_Idoperario);
		}
		return o;
	}

	public static Operarios createObj(HttpServletRequest req) throws TorqueException
	{
		Operarios o =  BaseOperariosHelper.getOperarios(req);
			 o.setIdoperario(WebUtils.getintParam(req, getIdoperarioName(o)));
		
			 		o.setIdcategoria(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIdcategoriaName(o)))));
		
			 o.setReferencia(WebUtils.getStringParam(req, getReferenciaName(o)));
		
			 o.setNif(WebUtils.getStringParam(req, getNifName(o)));
		
			 o.setNombre(WebUtils.getStringParam(req, getNombreName(o)));
		
			 o.setApellidouno(WebUtils.getStringParam(req, getApellidounoName(o)));
		
			 o.setApellidodos(WebUtils.getStringParam(req, getApellidodosName(o)));
		
			 o.setFechaalta(WebUtils.getStringParam(req, getFechaaltaName(o)));
		
			 o.setFechabaja(WebUtils.getStringParam(req, getFechabajaName(o)));
		
			 o.setNumeross(WebUtils.getStringParam(req, getNumerossName(o)));
		
			 o.setDireccion(WebUtils.getStringParam(req, getDireccionName(o)));
		
			 o.setCp(WebUtils.getStringParam(req, getCpName(o)));
		
			 		o.setIdlocalidad(Integer.parseInt(FormatUtils.getFkIdFromString(WebUtils.getStringParam(req, getIdlocalidadName(o)))));
		
			 o.setTelefono(WebUtils.getStringParam(req, getTelefonoName(o)));
		
			 o.setMovil(WebUtils.getStringParam(req, getMovilName(o)));
		
			 o.setEmail(WebUtils.getStringParam(req, getEmailName(o)));
		
			 o.setCoste(WebUtils.getdoubleParam(req, getCosteName(o)));
		
			 o.setExterno(WebUtils.getintParam(req, getExternoName(o)));
		
			 o.setObservaciones(WebUtils.getStringParam(req, getObservacionesName(o)));
		
			return o;
	}
}
