package net.idtoki.aveobras.helper;

import net.idtoki.aveobras.model.Clientes;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ClientesHelper
    extends net.idtoki.aveobras.helper.BaseClientesHelper
{
		    			public ClientesHelper()
    {
        super();
    }
    public ClientesHelper(Clientes obj)
    {
        super(obj);
    }
}


