package net.idtoki.aveobras.group;


import java.sql.Connection;
import java.util.List;
import java.util.logging.Logger;

//Torque classes
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import net.zylk.torque.group.BaseGroupBean;

// Local classes
import net.idtoki.aveobras.model.UejecucionesPeer;
import net.idtoki.aveobras.model.Uejecuciones;

/**
 * This class was autogenerated by Torque on:
 *
 * [Wed Oct 25 17:01:04 CEST 2006]
 *
 */
public abstract class BaseUejecucionesGroupBean
    extends BaseGroupBean
{

    /** el logger para esta clase */
    private static final Logger logger = Logger
			.getLogger("net.idtoki.aveobras.BaseUejecucionesGroup");

    /**
     * @return the map builder for this peer
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */

	public void setUejecucioness(Criteria criteria, boolean paginado) {
		this.setElementos(criteria, paginado);
	}

	public Uejecuciones getUejecuciones() {
		return (Uejecuciones) getNext();
	}

	public Uejecuciones getUejecuciones(int posicion) {
		return (Uejecuciones) get(posicion);
	}


	//EHI : Implementacion de los metodos abstractos de la clase padre
	public List abstractSelect(Criteria c) throws TorqueException {
		return UejecucionesPeer.doSelect(c);
	}

	public List abstractVillageRecords(Criteria c) throws TorqueException {
		return UejecucionesPeer.doSelectVillageRecords(c);
	}

	public void abstractSave(Connection conn) throws TorqueException {
		Uejecuciones element = null;
		while (this.next()) {
			element = this.getUejecuciones();
			element.save(conn);
		}
	}

	public void abstractDel(Connection conn) throws TorqueException {
		throw new TorqueException();
	}

	public String getDatabaseName(){
		return "AVEOBRAS-DB";
	}
}





