package net.idtoki.aveobras.controller;

import java.io.IOException;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.idtoki.aveobras.group.CategoriasGroupBean;
import net.idtoki.aveobras.helper.CategoriasHelper;
import net.idtoki.aveobras.helper.OperariosHelper;
import net.idtoki.aveobras.manager.CategoriasManager;
import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.web.WebUtils;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class CategoriasController
    extends net.idtoki.aveobras.controller.BaseCategoriasController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.controller.CategoriasController");

 public void init()
 {
  super.init();
  //Aqui se registran los metodos que no se quieran repetir de otros sitios.
  //por ejemplo igual quieres tener los metodos de generacion de ajax
  // en un paquete aparte y no copiarlos por aqui,  sino tenerlos disponibles
  //para todas las aplicaciones sin repetirlos en todos los sitios, pues los registras
  //y punto!!
 }
 
 public void serviceCategoriasUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
			 CategoriasHelper.IDCATEGORIA_GET_METHOD_NAME,
			 CategoriasHelper.DESCRIPCION_GET_METHOD_NAME};
	 String param =  WebUtils.getStringParam(request, "value");
	 
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new OperariosHelper().getIdcategoriaName());
	 
	 CategoriasGroupBean mgb = CategoriasManager.getCategoriass(CategoriasManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(mgb.getAlmacen(),methodos, CategoriasHelper.COMPLEX_ID_GET_METHOD,"Categorias"));
 }   
}


