package net.idtoki.aveobras.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import net.idtoki.aveobras.group.ClientesGroupBean;
import net.idtoki.aveobras.group.LocalidadesGroupBean;
import net.idtoki.aveobras.helper.ClientesHelper;
import net.idtoki.aveobras.helper.LocalidadesHelper;
import net.idtoki.aveobras.helper.ObrasHelper;
import net.idtoki.aveobras.manager.ClientesManager;
import net.idtoki.aveobras.manager.LocalidadesManager;
import net.idtoki.aveobras.model.Clientes;
import net.idtoki.aveobras.model.ClientesPeer;
import net.idtoki.aveobras.model.LocalidadesPeer;
import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class ClientesController
    extends net.idtoki.aveobras.controller.BaseClientesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.controller.ClientesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer cliente_transformer = null; 
 private Transformer clientes_transformer = null;  

 public void init(ServletConfig config)
 {
  super.init();
  ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/aveobras/app/config/app-config");
  ServletContext context = config.getServletContext();
  File cliente = new File(resource.getString("app.xsl.templates.dir")+"/PdfCliente.xslt");
  Source xslSource = new StreamSource(cliente);
  File clientes = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaCliente.xslt");
  Source xslSourceT = new StreamSource(clientes); 	  
  try{
	  cliente_transformer = tFactory.newTransformer(xslSource);
	  clientes_transformer = tFactory.newTransformer(xslSourceT);
  }catch (Exception e){
    e.printStackTrace();
  }  
 }
 
 public void serviceAddClientes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
		//recojo los parametros del formulario y doy de alta un nuevo Cliente
	 try
	 {
		 utf8RequestService(request);
		 Clientes cl = ClientesHelper.createObj(request);
		 ClientesGroupBean cgb = new ClientesGroupBean();
		 cl.setFechaalta(FormatUtils.ddmmaaaa2aaaammdd(cl.getFechaalta(),"-",""));
		 cl.setFechabaja(FormatUtils.ddmmaaaa2aaaammdd(cl.getFechabaja(),"-",""));
		 cgb.setElemento(cl);
		 cgb.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }
 
 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 } 
 
 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 		{
 			//c.clear();
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 			{
 			//c.clear();
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

 private Criteria criteriaClientesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
	  String param =  WebUtils.getStringParam(request, new LocalidadesHelper().getIdlocalidadName());
	  if(param != null)
			 TorqueUtils.addEqualCriteria(c,ClientesPeer.IDLOCALIDAD,param);	 
 	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
 	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
 	  //System.out.println("----query:"+paramQuery+"----col:"+paramSortCol+"----dir:"+paramSortDir+"----filtro:"+paramFiltro);
 	  c = ordenacion(c,paramSortCol,paramSortDir);

 	  return c;
 } 
 
 public void  serviceClientesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =ClientesManager.buildSearchCriteria(dgb); 
	 c =criteriaClientesTableContent(request,c);	 
	 ClientesGroupBean cgb = ClientesManager.getClientess(c);
	 dgb.setTotalSize(cgb.getTotalSize());
	  
	 String[] methodos= new String[] {
			 ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.REFERENCIA_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed",			 
//			 ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed",			 
			 ClientesHelper.CONTACTO_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.WWW_GET_METHOD_NAME+"ClientesParsed",			 
//			 ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed",
				"getEditClientes",
				"getDeleteClientes"
				};
	  
	 xmlResponseService(response,AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(
			  										cgb.getAlmacen(),
			  										methodos,
			  										ClientesHelper.IDCLIENTE_GET_METHOD_NAME, dgb,"ISO-8859-1")); 
 }
 
 public void serviceClientesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
			 ClientesHelper.IDCLIENTE_GET_METHOD_NAME, 
			 ClientesHelper.CIF_GET_METHOD_NAME,
			 ClientesHelper.NOMBRE_GET_METHOD_NAME
			 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
			 param =  WebUtils.getStringParam(request, new ObrasHelper().getIdclienteName());	 
	 ClientesGroupBean cgb = ClientesManager.getClientess(ClientesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(cgb.getAlmacen(),methodos, ClientesHelper.COMPLEX_ID_GET_METHOD,"Clientes"));
 }
 
 protected StringBuffer updateIdlocalidadResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getIdlocalidadClientesParsed());
   }
 
 protected StringBuffer updateCifResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getCifClientesParsed());
   }
 
 protected StringBuffer updateReferenciaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getReferenciaClientesParsed());
   }
 
 protected StringBuffer updateNombreResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getNombreClientesParsed());
   }
 
 protected StringBuffer updateRazonsocialResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getRazonsocialClientesParsed());
   }
 
 protected StringBuffer updateContactoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getContactoClientesParsed());
   }
 
 protected StringBuffer updateTelefonoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(ClientesManager.getClientes(Integer.parseInt(a.get(0).toString())).getTelefonoClientesParsed());
   } 
 
 public void serviceDeleteClientes(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
		 if (ClientesManager.borraClientes(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 } 
 
 public void serviceClientesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "clientes.IDCLIENTE");
  if (claveId!=-1)
  {
	  c.add(ClientesPeer.IDCLIENTE, claveId);
  }
  c.addAscendingOrderByColumn(ClientesPeer.IDCLIENTE);
  ClientesGroupBean trgb = ClientesManager.getClientess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
			  ClientesHelper.IDCLIENTE_GET_METHOD_NAME,
				 ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.CONTACTO_GET_METHOD_NAME+"ClientesParsed",				 
				 ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.REFERENCIA_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed",			 
				 ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.WWW_GET_METHOD_NAME+"ClientesParsed",			 
				 ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed"		  
	  			};
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");
  }
  xmlResponseService(response, cadena);
 } 
 
 public void serviceClientesLocalidad(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "localidades.IDLOCALIDAD");
  if (claveId!=-1)
  {
	  c.add(LocalidadesPeer.IDLOCALIDAD, claveId);
  }
  c.addAscendingOrderByColumn(LocalidadesPeer.IDLOCALIDAD);
  LocalidadesGroupBean trgb = LocalidadesManager.getLocalidadess(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><clientes.IDLOCALIDAD>" + trgb.getLocalidades(0).getIdlocalidad() + "-" + trgb.getLocalidades(0).getNombreLocalidadesParsed() + "</clientes.IDLOCALIDAD></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 } 
 
 public void serviceGetClientesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
			  ClientesHelper.IDCLIENTE_GET_METHOD_NAME,
				 ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.CONTACTO_GET_METHOD_NAME+"ClientesParsed",				 
				 ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.REFERENCIA_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed",			 
				 ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.MOVIL_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed",
				 ClientesHelper.WWW_GET_METHOD_NAME+"ClientesParsed",			 
				 ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed"	
			 };
	  
	 
	 ClientesGroupBean tgb = new ClientesGroupBean();
	 try
	{
		tgb.setElemento(ClientesHelper.getClientes(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), cliente_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=clienteDetalle.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close();
	
 }  
 
 public void serviceClientesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	  Criteria c= new Criteria();
	  String paramQuery =  WebUtils.getStringParam(request, "query");
	  if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		  c = ClientesManager.buildSearchCriteria(paramQuery);   
	  c =criteriaClientesTableContent(request,c);	    
  ClientesGroupBean tgb = ClientesManager.getClientess(c);
  
  String[] methodos= new String[] {	
			 ClientesHelper.CIF_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.NOMBRE_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.IDLOCALIDAD_GET_METHOD_NAME+"ClientesParsed",			 
//			 ClientesHelper.FECHAALTA_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.FECHABAJA_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.REFERENCIA_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.RAZONSOCIAL_GET_METHOD_NAME+"ClientesParsed",			 
			 ClientesHelper.CONTACTO_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.DIRECCION_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.CP_GET_METHOD_NAME+"ClientesParsed",
			 ClientesHelper.TELEFONO_GET_METHOD_NAME+"ClientesParsed"
//			 ClientesHelper.FAX_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.EMAIL_GET_METHOD_NAME+"ClientesParsed",
//			 ClientesHelper.WWW_GET_METHOD_NAME+"ClientesParsed",			 
//			 ClientesHelper.OBSERVACIONES_GET_METHOD_NAME+"ClientesParsed",
  			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), clientes_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=ListaClientes.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close();

 } 
}


