package net.idtoki.aveobras.controller;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.ResourceBundle;
import java.util.logging.Logger;

import javax.servlet.ServletConfig;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamSource;

import net.idtoki.aveobras.group.ObrasGroupBean;
import net.idtoki.aveobras.group.SubcapitulosGroupBean;
import net.idtoki.aveobras.group.UejecucionesGroupBean;
import net.idtoki.aveobras.helper.IncidenciasHelper;
import net.idtoki.aveobras.helper.ObrasHelper;
import net.idtoki.aveobras.helper.PartesHelper;
import net.idtoki.aveobras.helper.SubcapitulosHelper;
import net.idtoki.aveobras.helper.UejecucionesHelper;
import net.idtoki.aveobras.manager.ObrasManager;
import net.idtoki.aveobras.manager.SubcapitulosManager;
import net.idtoki.aveobras.manager.UejecucionesManager;
import net.idtoki.aveobras.model.MaquinariasPeer;
import net.idtoki.aveobras.model.ObrasPeer;
import net.idtoki.aveobras.model.SubcapitulosPeer;
import net.idtoki.aveobras.model.Uejecuciones;
import net.idtoki.aveobras.model.UejecucionesPeer;
import net.zylk.tools.ajax.AjaxUtils;
import net.zylk.tools.ajax.AjaxUtils.DinamicGridBean;
import net.zylk.tools.format.FormatUtils;
import net.zylk.tools.pdf.PdfUtils;
import net.zylk.tools.xml.XmlUtils;
import net.zylk.torque.TorqueUtils;
import net.zylk.web.WebUtils;

import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Apr 19 12:33:52 CEST 2006]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UejecucionesController
    extends net.idtoki.aveobras.controller.BaseUejecucionesController
{
 private static final Logger logger = Logger.getLogger("net.idtoki.aveobras.controller.UejecucionesController");
 private TransformerFactory tFactory = TransformerFactory.newInstance();
 private Transformer uejecucion_transformer = null; 
 private Transformer uejecucions_transformer = null;   

 public void init(ServletConfig config)
 {
  super.init();
  ResourceBundle resource = ResourceBundle.getBundle("net/idtoki/aveobras/app/config/app-config");
  ServletContext context = config.getServletContext();
  File uejecucion = new File(resource.getString("app.xsl.templates.dir")+"/PdfUejecucion.xslt");
  Source xslSource = new StreamSource(uejecucion);
  File uejecucions = new File(resource.getString("app.xsl.templates.dir")+"/PdfListaUejecucion.xslt");
  Source xslSourceT = new StreamSource(uejecucions); 	  
  try{
	  uejecucion_transformer = tFactory.newTransformer(xslSource);
	  uejecucions_transformer = tFactory.newTransformer(xslSourceT);
  }catch (Exception e){
    e.printStackTrace();
  }  
 }
 
 public void serviceAddUejecuciones(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
		//recojo los parametros del formulario y doy de alta un nuevo Cliente
	 try
	 {
		 utf8RequestService(request);
		 Uejecuciones ue = UejecucionesHelper.createObj(request);
		 UejecucionesGroupBean uegb = new UejecucionesGroupBean();
		 ue.setFechacomienzo(FormatUtils.ddmmaaaa2aaaammdd(ue.getFechacomienzo(),"-",""));
		 ue.setFechafin(FormatUtils.ddmmaaaa2aaaammdd(ue.getFechafin(),"-",""));
		 if (ue.getImporte()==-1)
			 ue.setImporte(0);
		 if (ue.getHorasestimadas()==-1)
			 ue.setHorasestimadas(0);
		 uegb.setElemento(ue);
		 uegb.save();
	 }
	 catch(TorqueException te)
	 {
		 response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	 }
 }
 
 public StringBuffer replaceStringBuffer (StringBuffer strBA, String strOrigen, String strDestino) 
 {
	 return new StringBuffer(strBA.toString().replaceAll(strOrigen,strDestino));
 } 
 
 private Criteria ordenacion(Criteria c,String CampoOrdenacion,String OrdenOrdenacion) 
 { 
 	if((OrdenOrdenacion != null )&& (OrdenOrdenacion.compareTo("ASC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 		{
 			//c.clear();
 			c.addAscendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	if  ((OrdenOrdenacion != null) && (OrdenOrdenacion.compareTo("DESC")==0))
 		if ((CampoOrdenacion != null)) //&& (CampoOrdenacion.compareTo("nombre")==0))
 			{
 			//c.clear();
 			c.addDescendingOrderByColumn(CampoOrdenacion.toString());
 		}
 	return c;
 }

 private Criteria filtro(Criteria c,int filtro) 
 { 
 	String cadena = null;
 	 switch (filtro)
 	 {
 	 case 1:
		  //Operarios en Activo
		  c.add(UejecucionesPeer.FECHAFIN,(Object)cadena,Criteria.ISNULL);
 		  break;
 	 case 2:
		  //Operarios dados de baja
		  c.add(UejecucionesPeer.FECHAFIN,(Object)cadena,Criteria.ISNOTNULL);
		  break;
 	 default:
 		 //todas las obras
 		 break;
 	 }
 	return c;
 }
 private Criteria criteriaUejecucionesTableContent(HttpServletRequest request,Criteria c) throws IOException, ServletException
 {
	  String param =  WebUtils.getStringParam(request, new ObrasHelper().getIdobraName());
	  int paramFiltro =  WebUtils.getintParam(request, "filtro");
	  if(param != null)
			 TorqueUtils.addEqualCriteria(c,UejecucionesPeer.IDOBRA,param);
	  param =  WebUtils.getStringParam(request, new SubcapitulosHelper().getIdsubcapituloName());
	  if(param != null)
			 TorqueUtils.addEqualCriteria(c,UejecucionesPeer.IDSUBCAPITULO,param);		 
 	  String paramSortCol =  WebUtils.getStringParam(request, "sort_col");
 	  String paramSortDir =  WebUtils.getStringParam(request, "sort_dir");
 	  //System.out.println("----query:"+paramQuery+"----col:"+paramSortCol+"----dir:"+paramSortDir+"----filtro:"+paramFiltro);
	  c = filtro(c,paramFiltro);
	  c = ordenacion(c,paramSortCol,paramSortDir);

 	  return c;
 } 
 
 public void  serviceUejecucionesTableContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 int numElemPedidosBD = 40;
	 int gap = 0;//gap = viewedRows - numElemVisiblesUltPag	  
	 DinamicGridBean dgb = WebUtils.getDinamicGridBeanParam(request,numElemPedidosBD,gap); 
	 Criteria c =UejecucionesManager.buildSearchCriteria(dgb); 
	 c =criteriaUejecucionesTableContent(request,c);	 
	 	  
	 UejecucionesGroupBean cgb = UejecucionesManager.getUejecucioness(c);
	 dgb.setTotalSize(cgb.getTotalSize());	  
	  
	 String[] methodos= new String[] {
			 UejecucionesHelper.REFERENCIA_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.IDOBRA_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.IDSUBCAPITULO_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.FECHACOMIENZO_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.FECHAFIN_GET_METHOD_NAME+"UejecucionesParsed",
//			 UejecucionesHelper.HORASESTIMADAS_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.IMPORTE_GET_METHOD_NAME+"UejecucionesParsed",
//			 UejecucionesHelper.DESCRIPCION_GET_METHOD_NAME+"UejecucionesParsed",
//			 UejecucionesHelper.OBSERVACIONES_GET_METHOD_NAME+"UejecucionesParsed",
				"getEditUejecuciones",
				"getDeleteUejecuciones"
				};
	  
	 xmlResponseService(response,AjaxUtils.buildXmlAjaxResponseTableContentFromListObj(
			  										cgb.getAlmacen(),
			  										methodos,
			  										UejecucionesHelper.IDUEJECUCION_GET_METHOD_NAME, dgb,"ISO-8859-1")); 
 }
 
 public void serviceUejecucionesUlContent(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] methodos= new String[] {
			 UejecucionesHelper.IDUEJECUCION_GET_METHOD_NAME, 
			 UejecucionesHelper.IDSUBCAPITULO_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.IDOBRA_GET_METHOD_NAME+"UejecucionesParsed"
	 };
	 String param =  WebUtils.getStringParam(request, "value");
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new PartesHelper().getIduejecucionName());
	 if(param==null || param.length() <= 0)
		 param =  WebUtils.getStringParam(request, new IncidenciasHelper().getIduejecucionName());	 
	 UejecucionesGroupBean cgb = UejecucionesManager.getUejecucioness(UejecucionesManager.buildSearchCriteria(param));
	 simpleResponseService(response, AjaxUtils.buildAjaxULContentFromListObj(cgb.getAlmacen(),methodos, UejecucionesHelper.COMPLEX_ID_GET_METHOD,"Uejecuciones"));
 }
 
 protected StringBuffer updateIdobraResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(UejecucionesManager.getUejecuciones(Integer.parseInt(a.get(0).toString())).getIdobraUejecucionesParsed());
   }
 
 protected StringBuffer updateIdsubcapituloResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(UejecucionesManager.getUejecuciones(Integer.parseInt(a.get(0).toString())).getIdsubcapituloUejecucionesParsed());
   } 
 
 protected StringBuffer updateReferenciaResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(UejecucionesManager.getUejecuciones(Integer.parseInt(a.get(0).toString())).getReferenciaUejecucionesParsed());
   }  
 
 protected StringBuffer updateFechacomienzoResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(UejecucionesManager.getUejecuciones(Integer.parseInt(a.get(0).toString())).getFechacomienzoUejecucionesParsed());
   } 
 
 protected StringBuffer updateFechafinResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(UejecucionesManager.getUejecuciones(Integer.parseInt(a.get(0).toString())).getFechafinUejecucionesParsed());
   } 
 
 protected StringBuffer updateImporteResponseCallBack(String s)
 {
  ArrayList a = AjaxUtils.splitIdFields(s);
    	return new StringBuffer(UejecucionesManager.getUejecuciones(Integer.parseInt(a.get(0).toString())).getImporteUejecucionesParsed());
   } 
 
 public void serviceDeleteUejecuciones(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 int idBorrar=-1;
	 idBorrar=WebUtils.getintParam(request, "borrarId");
	 if (idBorrar!=-1)
		 if (UejecucionesManager.borraUejecuciones(idBorrar))
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlOKResponse("ISO-8859-1"));
		 else
			 WebUtils.writeXmlResponse(response,XmlUtils.buildXmlNotOKResponse("ISO-8859-1"));			 
 } 
 
 public void serviceUejecucionesElement(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  StringBuffer cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "uejecuciones.IDUEJECUCION");
  if (claveId!=-1)
  {
	  c.add(UejecucionesPeer.IDUEJECUCION, claveId);
  }
  c.addAscendingOrderByColumn(UejecucionesPeer.IDUEJECUCION);
  UejecucionesGroupBean trgb = UejecucionesManager.getUejecucioness(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  String [] parametros={
			  UejecucionesHelper.IDUEJECUCION_GET_METHOD_NAME,
				 UejecucionesHelper.IDOBRA_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.IDSUBCAPITULO_GET_METHOD_NAME+"UejecucionesParsed",	
				 UejecucionesHelper.FECHACOMIENZO_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.FECHAFIN_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.REFERENCIA_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.HORASESTIMADAS_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.IMPORTE_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.DESCRIPCION_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.OBSERVACIONES_GET_METHOD_NAME+"UejecucionesParsed"				 
	  			};
	  cadena=trgb.buildXml(parametros,null,"ISO-8859-1");
  }
  xmlResponseService(response, cadena);
 } 
 
 public void serviceUejecucionesObra(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "obras.IDOBRA");
  if (claveId!=-1)
  {
	  c.add(ObrasPeer.IDOBRA, claveId);
  }
  c.addAscendingOrderByColumn(ObrasPeer.IDOBRA);
  ObrasGroupBean trgb = ObrasManager.getObrass(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><uejecuciones.IDOBRA>" + trgb.getObras(0).getIdobra() + "-" + trgb.getObras(0).getNombreObrasParsed()+ " (" + trgb.getObras(0).getIdclienteObrasParsed() + ")" + "</uejecuciones.IDOBRA></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 }
 
 public void serviceUejecucionesSubcapitulo(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
  String cadena=null;
  Criteria c= new Criteria();
  int claveId=-1;
  claveId=WebUtils.getintParam(request, "subcapitulos.IDSUBCAPITULO");
  if (claveId!=-1)
  {
	  c.add(SubcapitulosPeer.IDSUBCAPITULO, claveId);
  }
  c.addAscendingOrderByColumn(SubcapitulosPeer.IDSUBCAPITULO);
  SubcapitulosGroupBean trgb = SubcapitulosManager.getSubcapituloss(c);
  
  if (trgb.getTotalSize()!=0)
  {
	  cadena = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>";
	  cadena = cadena + "<result><uejecuciones.IDSUBCAPITULO>" + trgb.getSubcapitulos(0).getIdsubcapitulo() + "-" + trgb.getSubcapitulos(0).getNombreSubcapitulosParsed() + " (" + trgb.getSubcapitulos(0).getIdcapituloSubcapitulosParsed()+ ")" + "</uejecuciones.IDSUBCAPITULO></result>";
  }
  
  xmlResponseService(response, new StringBuffer(cadena));
 } 
 
 public void serviceGetUejecucionesDetallePdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	 String[] getMethodos= new String[] {
			  UejecucionesHelper.IDUEJECUCION_GET_METHOD_NAME,
				 UejecucionesHelper.IDOBRA_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.IDSUBCAPITULO_GET_METHOD_NAME+"UejecucionesParsed",	
				 UejecucionesHelper.REFERENCIA_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.FECHACOMIENZO_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.FECHAFIN_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.HORASESTIMADAS_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.IMPORTE_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.DESCRIPCION_GET_METHOD_NAME+"UejecucionesParsed",
				 UejecucionesHelper.OBSERVACIONES_GET_METHOD_NAME+"UejecucionesParsed"
			 };
	  
	 
	 UejecucionesGroupBean tgb = new UejecucionesGroupBean();
	 try
	{
		tgb.setElemento(UejecucionesHelper.getUejecuciones(request));
	} catch (TorqueException e)
	{
		logger.severe(e.getMessage());
	}
	
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(getMethodos, null,"ISO-8859-1"),"n/a"," "), uejecucion_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=uejecucionDetalle.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close();
	
 }  
 
 public void serviceUejecucionesTableContentPdf(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
 {
	 utf8RequestService(request);
	  Criteria c= new Criteria();
	  String paramQuery =  WebUtils.getStringParam(request, "query");
	  if ((paramQuery != null)&& (paramQuery.compareTo("")!=0) )
		  c = UejecucionesManager.buildSearchCriteria(paramQuery);   
	  c =criteriaUejecucionesTableContent(request,c);	 
   
  UejecucionesGroupBean tgb = UejecucionesManager.getUejecucioness(c);
  
  String[] methodos= new String[] {	
			 UejecucionesHelper.IDOBRA_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.IDSUBCAPITULO_GET_METHOD_NAME+"UejecucionesParsed",	
			 UejecucionesHelper.REFERENCIA_GET_METHOD_NAME+"UejecucionesParsed",	
			 UejecucionesHelper.FECHACOMIENZO_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.FECHAFIN_GET_METHOD_NAME+"UejecucionesParsed",
//			 UejecucionesHelper.HORASESTIMADAS_GET_METHOD_NAME+"UejecucionesParsed",
			 UejecucionesHelper.IMPORTE_GET_METHOD_NAME+"UejecucionesParsed",
//			 UejecucionesHelper.DESCRIPCION_GET_METHOD_NAME+"UejecucionesParsed",
//			 UejecucionesHelper.OBSERVACIONES_GET_METHOD_NAME+"UejecucionesParsed"
			};
  
	 byte[] content =  PdfUtils.getBytes(replaceStringBuffer(tgb.buildXml(methodos, null,"ISO-8859-1"),"n/a"," "), uejecucions_transformer,"ISO-8859-1");
	   response.addHeader("content-disposition","attachment;filename=ListaUejecucion.pdf");
	   response.setContentType("application/pdf");
	   response.setHeader("Cache-Control", "");//para que funcione en IE
	   response.setContentLength(content.length);
	   response.getOutputStream().write(content);
	   response.getOutputStream().flush();  
	   response.getOutputStream().close();

 } 
 
} 



